Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2020-10, with the labels that each got.

#96 feat(pull to refresh): add refetching in every screen
  src/components/CardList.js
  src/components/CategoryList.js
  src/components/TextList.js
  src/components/screens/About.js
  src/components/screens/Carousel.js
  src/components/screens/Service.js
  src/screens/AboutScreen.js
  src/screens/CompanyScreen.js
  src/screens/DetailScreen.js
  src/screens/HomeScreen.js
  src/screens/HtmlScreen.js
  src/screens/IndexScreen.js
  src/screens/ServiceScreen.js
Labels: enhancement

#99 feat(NetInfo): refactor usage on app load
  src/NetworkProvider.js
  src/index.js
Labels: enhancement

#102 Refetch should not be triggered when offline
  src/screens/AboutScreen.js
  src/screens/CompanyScreen.js
  src/screens/DetailScreen.js
  src/screens/HtmlScreen.js
  src/screens/IndexScreen.js
  src/screens/ServiceScreen.js
Labels: bug, enhancement

#103 fix: revert additional check in HtmlScreen
  src/screens/HtmlScreen.js
Labels: bug

#104 Refactored main queries file
  src/queries/index.js
  src/screens/FormScreen.js
Labels: refactoring

#106 fix: add missing file referenced in queries
  src/queries/appUserContent.js
Labels: bug

#105 feat(button): new style on landscape mode
  src/components/Button.js
Labels: enhancement

#107 feat(detail and html screens): condition for landscape mode
  src/OrientationProvider.js
  src/components/CardList.js
  src/components/HtmlView.js
  src/components/ImagesCarousel.js
  src/components/Wrapper.js
  src/components/screens/EventRecord.js
  src/components/screens/NewsItem.js
  src/components/screens/PointOfInterest.js
  src/components/screens/Tour.js
  src/screens/FormScreen.js
  src/screens/HtmlScreen.js
Labels: enhancement

#108 feat(cardListitem): new style condition for landscape mode
  src/components/CardList.js
  src/components/CardListItem.js
  src/components/SafeAreaViewFlex.js
  src/screens/IndexScreen.js
Labels: enhancement

#112 feat(service boxes): add sizing and positioning based on orientation
  src/components/ServiceBox.js
  src/components/screens/Service.js
  src/screens/CompanyScreen.js
  src/screens/ServiceScreen.js
Labels: enhancement

#115 feat: add text helper for formatting subtitle
  src/helpers/index.js
  src/helpers/textHelper.js
  src/screens/HomeScreen.js
  src/screens/IndexScreen.js
Labels: enhancement
