Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2021-11, with the labels that each got.

#389 fix: correct translation of verified verification status
  src/config/texts.js
Labels: refactoring

#390 fix: adjust paddings for list items with switches
  src/components/ToggleListItem.js
  src/components/wasteCalendar/WasteReminderSettings.tsx
Labels: refactoring

#387 feat(image): set original source on cache fail
  src/components/Image.js
Labels: enhancement

#392 BBNavi: text adjustments
  src/components/infoCard/AddressSection.tsx
  src/config/texts.js
  src/hooks/openWebScreen.ts
Labels: enhancement

#388 BB Bus: always use cache first
  src/config/consts.js
  src/helpers/refreshIntervalHelper.js
Labels: enhancement

#393 Encounter: added more info and poi category
  src/components/encounter/EncounterWelcome.tsx
  src/config/texts.js
  src/hooks/index.js
  src/hooks/staticContent.ts
  src/queries/pointsOfInterest.js
  src/screens/EncounterHomeScreen.tsx
Labels: enhancement

#394 fix(location overview): category id not being used
  src/components/map/LocationOverview.tsx
  src/screens/IndexScreen.js
Labels: bug

#397 Fix: encounter information icons not clickable on android
  src/screens/EncounterDataScreen.tsx
  src/screens/EncounterHomeScreen.tsx
Labels: bug

#406 Encounter: minor improvements
  src/screens/EncounterDataScreen.tsx
Labels: bug, enhancement
