Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2021-01, with the labels that each got.

#145 chore: upgrade Expo SDK to 40
  package.json
  yarn.lock
Labels: enhancement

#149 chore(IndexScreen): remove unnecessary style
  src/screens/IndexScreen.js
Labels: refactoring

#148 chore(queries): remove unnecessary offset option
  src/queries/pointsOfInterestAndTours.js
Labels: refactoring

#147 refactor(CategoryList): add checks for data and intro text
  src/components/CategoryList.js
Labels: refactoring

#153 fix(location overview): fetch policy
  src/components/map/LocationOverview.tsx
  src/helpers/graphqlHelper.js
Labels: enhancement

#159 chore(feedback form): small correction on check-box text
  src/screens/FormScreen.js
Labels: enhancement

#150 fix(push notification): navigation on interaction
  src/components/screens/EventRecord.js
  src/components/screens/NewsItem.js
  src/components/screens/Tour.js
  src/config/consts.js
  src/config/texts.js
  src/helpers/index.js
  src/helpers/queryDataParser.js
  src/helpers/queryHelper.js
  src/screens/HomeScreen.js
Labels: bug

#160 fix(parsing public json content): catch errors on JSON.parse
  src/components/screens/About.js
  src/components/screens/HomeCarousel.js
  src/components/screens/Service.js
  src/index.js
  src/screens/AboutScreen.js
  src/screens/CompanyScreen.js
  src/screens/ServiceScreen.js
Labels: bug, enhancement

#161 style(header title): left aligned
  src/navigation/defaultStackNavigatorConfig.js
Labels: enhancement

#163 fix(map): hide POI map in offline
  src/components/map/LocationOverview.tsx
  src/components/screens/PointOfInterest.js
Labels: bug, enhancement, refactoring

#165 fix(image loading spinner android): update react-native-elements from 1.1.0 to 1.2.7
  package.json
  src/components/CardListItem.js
  src/components/Image.js
  src/components/Logo.js
  src/components/screens/Service.js
  src/components/weather/DailyWeather.tsx
  src/components/weather/HourlyWeather.tsx
  src/components/widgets/WeatherWidget.tsx
  src/screens/CompanyScreen.js
  src/screens/ServiceScreen.js
  yarn.lock
Labels: bug, enhancement

#166 fix(safe area insets): upgrade safe area view
  package.json
  src/index.js
  yarn.lock
Labels: bug

#169 refactor(construction site): use textlistitem for better maintainability
  src/screens/ConstructionSiteOverviewScreen.js
Labels: enhancement

#171 Add form as route for drawer
  src/navigation/AppStackNavigator.js
Labels: bug, enhancement

#172 Switch rendering of tours and points of interest
  src/components/CategoryList.js
  src/config/texts.js
  src/screens/HomeScreen.js
Labels: enhancement

#173 Add a notice at the bottom of TMB contents
  src/components/TMB/Notice.js
  src/components/screens/EventRecord.js
  src/components/screens/PointOfInterest.js
  src/components/screens/Tour.js
  src/config/styles/html.js
  src/config/texts.js
Labels: enhancement

#175 Show message on slider item
  src/components/Image.js
  src/components/ImageMessage.js
  src/components/ImagesCarousel.js
  src/components/ImagesCarouselItem.js
Labels: enhancement
