Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2021-09, with the labels that each got.

#273 feature(generic items): construction sites
  src/ConstructionSiteProvider.tsx
  src/components/widgets/ConstructionSiteWidget.tsx
  src/helpers/index.js
  src/helpers/momentHelper.js
  src/helpers/parser/constructionSiteParser.ts
  src/helpers/parser/index.ts
  src/helpers/parser/listItemParser.js
  src/hooks/constructionSites.ts
  src/hooks/index.js
  src/index.js
  src/jsonValidation/constructionSiteValidator.ts
  src/queries/constructionSite.js
  src/queries/index.js
  src/queries/types.js
  src/screens/ConstructionSiteDetailScreen.js
  src/screens/ConstructionSiteOverviewScreen.js
  src/types/ConstructionSite.ts
  src/types/ContentBlock.ts
  src/types/DataProvider.ts
  src/types/Date.ts
  src/types/GenericItem.ts
  src/types/MediaContent.ts
  src/types/index.ts
Labels: enhancement

#276 feat(matomo): add more device infos to tracking
  App.js
  package.json
  src/hooks/matomoHooks.js
  src/screens/HtmlScreen.js
  src/screens/IndexScreen.js
  src/screens/WebScreen.js
  yarn.lock
Labels: enhancement, dependencies

#292 ts config: apply expo setup
  package.json
  src/helpers/storageHelper.js
  src/pushNotifications/WasteReminder.ts
  tsconfig.json
Labels: refactoring

#295 chore(shareContent): improve type of openShare
  src/components/ShareHeader.tsx
  src/helpers/shareHelper.js
  src/hooks/openWebScreen.ts
Labels: enhancement, refactoring

#326 fix(require cycle): navigation config
  src/screens/DetailScreen.js
Labels: refactoring

#318 feature(encounter): basic layout for home screen
  app.json
  package.json
  src/config/Icon.tsx
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/helpers/storageHelper.js
  src/hooks/encounter/index.ts
  src/hooks/encounter/qr.ts
  src/hooks/encounter/user.ts
  src/hooks/index.js
  src/screens/EncounterHomeScreen.tsx
  src/screens/index.js
  src/types/Navigation.ts
  yarn.lock
Labels: enhancement
