Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2021-07, with the labels that each got.

#253 Refactor navigators with configs
  src/config/navigation/config.ts
  src/config/navigation/defaultStackConfig.tsx
  src/config/navigation/tabConfig.tsx
  src/navigation/AppStackNavigator.js
  src/navigation/AppStackNavigator.tsx
  src/navigation/DrawerNavigator.tsx
  src/navigation/MainTabNavigator.tsx
  src/navigation/Navigator.tsx
  src/screens/CompanyScreen.js
  src/screens/IndexScreen.js
  src/screens/ServiceScreen.js
  src/screens/TilesScreen.js
  src/screens/index.js
  src/types/Navigation.ts
  src/types/index.ts
Labels: refactoring

#254 chore(expo sdk): upgrade to 42
  package.json
  yarn.lock
Labels: dependencies, enhancement

#256 fix(default stack config): use headerRight config everywhere
  src/config/navigation/defaultStackConfig.tsx
Labels: bug

#257 chore: reorder navigator config for easier commenting
  src/config/navigation/config.ts
Labels: refactoring

#258 chore(navigation config): remove from global settings
  src/SettingsProvider.js
  src/config/consts.js
  src/config/navigation/defaultStackConfig.tsx
  src/config/navigation/index.ts
  src/config/navigation/tabConfig.tsx
  src/index.js
  src/navigation/CustomDrawerContentComponent.js
  src/navigation/DrawerNavigator.tsx
  src/navigation/DrawerNavigatorItems.js
  src/navigation/Navigator.tsx
  src/screens/HomeScreen.js
Labels: refactoring

#263 fix(drawer content): spilling over to the bottom
  src/navigation/CustomDrawerContentComponent.js
Labels: bug

#264 Refactor/sva 246 centralize font config
  App.js
  __tests__/components/__snapshots__/Button.test.js.snap
  __tests__/components/__snapshots__/Link.test.js.snap
  src/components/BB-BUS/IndexFilter.js
  src/components/BB-BUS/TextSearch.js
  src/components/Button.js
  src/components/HtmlView.js
  src/components/Label.js
  src/components/StorySection.js
  src/components/Text.js
  src/components/Title.js
  src/config/fonts.ts
  src/config/index.js
  src/config/styles/baseFontStyle.js
  src/config/styles/html.js
  src/navigation/DrawerNavigatorItems.js
  src/navigation/screenOptions.tsx
  src/screens/OParl/OParlPersonsScreen.tsx
  src/screens/OParl/OParlSearchScreen.tsx
  src/screens/WasteCollectionScreen.js
Labels: enhancement, refactoring

#270 Refactor/sva 247 centralize icons
  __tests__/components/Icon.test.js
  __tests__/components/__snapshots__/Icon.test.js.snap
  src/components/BackToTop.js
  src/components/CategoryListItem.js
  src/components/DropdownSelect.js
  src/components/HeaderLeft.tsx
  src/components/Icon.js
  src/components/Link.js
  src/components/OrientationAwareIcon.tsx
  src/components/Radiobutton.js
  src/components/SettingsListItem.js
  src/components/ShareHeader.tsx
  src/components/TabBarIcon.js
  src/components/TextListItem.tsx
  src/components/bookmarks/BookmarkHeader.tsx
  src/components/calendarArrows.tsx
  src/components/index.js
  src/components/infoCard/AddressSection.tsx
  src/components/infoCard/ContactSection.tsx
  src/components/infoCard/UrlSection.tsx
  src/components/oParl/Row.tsx
  src/components/oParl/previews/OParlPreviewEntry.tsx
  src/components/screens/LunchSection.tsx
  src/components/screens/Service.js
  src/components/screens/ServiceTiles.js
  src/components/screens/TourCard.js
  src/components/widgets/ConstructionSiteWidget.tsx
  src/components/widgets/DefaultWidget.tsx
  src/components/widgets/EventWidget.tsx
  src/components/widgets/LunchWidget.tsx
  src/config/Icon.tsx
  src/config/index.js
  src/config/navigation/tabConfig.tsx
  src/navigation/screenOptions.tsx
  src/screens/LunchScreen.js
  src/screens/OParl/OParlOverviewScreen.tsx
Labels: enhancement, refactoring

#272 fix(drawer): header height for android
  src/helpers/calendarHelper.ts
  src/helpers/headerHelper.ts
  src/helpers/index.js
  src/navigation/CustomDrawerContentComponent.js
Labels: bug, refactoring

#240 Epic/survey
  src/components/Button.js
  src/components/CommentSection.tsx
  src/components/DefaultKeyboardAvoidingView.tsx
  src/components/Results.tsx
  src/components/SurveyAnswer.tsx
  src/components/Text.js
  src/components/index.js
  src/config/colors.js
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/helpers/index.js
  src/helpers/surveyHelper.tsx
  src/hooks/index.js
  src/hooks/pullToRefetch.tsx
  src/hooks/surveyHooks.ts
  src/queries/survey.js
  src/screens/BB-BUS/IndexScreen.js
  src/screens/FormScreen.js
  src/screens/SurveyDetailScreen.tsx
  src/screens/SurveyOverviewScreen.tsx
  src/screens/index.js
  src/types/Navigation.ts
  src/types/Survey.ts
  src/types/index.ts
Labels: epic

#277 Feature: survey widget
  src/components/widgets/SurveyWidget.tsx
  src/components/widgets/Widgets.tsx
  src/config/Icon.tsx
  src/config/texts.js
Labels: enhancement

#234 Feature/accessibility improvements
  src/components/Button.js
  src/components/CardListItem.js
  src/components/CategoryList.js
  src/components/CategoryListItem.js
  src/components/HeaderLeft.tsx
  src/components/Image.js
  src/components/ImagesCarouselItem.js
  src/components/Link.js
  src/components/SectionHeader.tsx
  src/components/SettingsListItem.js
  src/components/ShareHeader.tsx
  src/components/TextListItem.tsx
  src/components/ToggleListItem.js
  src/components/VersionNumber.js
  src/components/bookmarks/BookmarkHeader.tsx
  src/components/infoCard/AddressSection.tsx
  src/components/infoCard/ContactSection.tsx
  src/components/infoCard/InfoCard.tsx
  src/components/infoCard/UrlSection.tsx
  src/components/oParl/previews/OParlPreviewEntry.tsx
  src/components/screens/About.js
  src/components/screens/EventRecord.js
  src/components/screens/LunchSection.tsx
  src/components/screens/NewsItem.js
  src/components/screens/OperatingCompany.tsx
  src/components/screens/PointOfInterest.js
  src/components/screens/Service.js
  src/components/screens/ServiceTiles.js
  src/components/screens/Tour.js
  src/components/screens/TourCard.js
  src/components/wasteCalendar/WasteReminderSettings.tsx
  src/config/Icon.tsx
  src/config/consts.js
  src/navigation/CustomDrawerContentComponent.js
  src/navigation/screenOptions.tsx
  src/screens/AboutScreen.js
  src/screens/FormScreen.js
  src/screens/SettingsScreen.js
  src/screens/WeatherScreen.js
Labels: enhancement

#281 fix(index screen): not updating on query variable change
  src/screens/IndexScreen.js
Labels: bug, enhancement

#283 chore(html table): exchange dependency
  package.json
  src/components/HtmlView.js
  yarn.lock
Labels: dependencies

#284 share logic in webScreen
  src/components/screens/NewsItem.js
  src/config/navigation/defaultStackConfig.tsx
  src/hooks/openWebScreen.ts
Labels: enhancement
