Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2021-02, with the labels that each got.

#178 fix(share icon and settings icon) removed paddingVertical
  src/components/Icon.js
  src/screens/BB-BUS/DetailScreen.js
  src/screens/BookmarkScreen.js
  src/screens/DetailScreen.js
Labels: bug

#182 Added logo to POIs
  src/components/screens/PointOfInterest.js
Labels: enhancement

#180 fix(location overview): crash at null value
  src/components/map/LocationOverview.tsx
Labels: bug

#183 Fix/sva 172 homescreen refreshing
  src/components/HomeSection.tsx
  src/components/ListComponent.js
  src/components/index.js
  src/components/screens/HomeCarousel.js
  src/components/widgets/ConstructionSiteWidget.tsx
  src/components/widgets/EventWidget.tsx
  src/components/widgets/WeatherWidget.tsx
  src/helpers/queryDataParser.js
  src/hooks/HomeRefresh.ts
  src/screens/HomeScreen.js
Labels: bug, enhancement, refactoring

#181 Chore/extract header left
  src/components/HeaderLeft.js
  src/components/index.js
  src/hooks/matomoHooks.js
  src/screens/BB-BUS/DetailScreen.js
  src/screens/BB-BUS/IndexScreen.js
  src/screens/BookmarkCategoryScreen.js
  src/screens/BookmarkScreen.js
  src/screens/ConstructionSiteDetailScreen.js
  src/screens/ConstructionSiteOverviewScreen.js
  src/screens/DetailScreen.js
  src/screens/FormScreen.js
  src/screens/HomeScreen.js
  src/screens/HtmlScreen.js
  src/screens/IndexScreen.js
  src/screens/SettingsScreen.js
  src/screens/WeatherScreen.js
  src/screens/WebScreen.js
Labels: enhancement

#186 fix(image copyrights): crashing on empty string
  src/components/Image.js
Labels: bug

#187 feat(filter): do not show a filter when there is just one entry
  src/components/DropdownHeader.js
Labels: enhancement

#190 fix(text): number encoded characters
  src/components/BB-BUS/Label.js
  src/components/BB-BUS/TextSearch.js
  src/components/Label.js
  src/components/Text.js
  src/components/Title.js
  src/navigation/DrawerNavigatorItems.js
Labels: bug, enhancement

#195 fix: add missing attributes to query
  src/queries/eventRecords.js
Labels: bug

#188 refactor(home screen): useHomeRefresh
  src/components/screens/About.js
  src/components/screens/Service.js
  src/screens/HomeScreen.js
Labels: refactoring

#192 Fix/ no link for incomplete address
  src/components/BB-BUS/Authority.js
  src/components/BB-BUS/Persons.js
  src/components/BB-BUS/helpers.js
  src/components/index.js
  src/components/infoCard/AddressSection.tsx
  src/components/infoCard/ContactSection.tsx
  src/components/infoCard/InfoCard.tsx
  src/components/infoCard/UrlSection.tsx
  src/components/infoCard/index.ts
  src/components/screens/EventRecord.js
  src/components/screens/InfoCard.js
  src/components/screens/LunchSection.tsx
  src/components/screens/OperatingCompany.tsx
  src/components/screens/OperatingCompanyInfo.js
  src/components/screens/PointOfInterest.js
  src/components/screens/Tour.js
  src/components/screens/index.js
  src/helpers/addressHelper.js
  src/types/Address.ts
  src/types/Contact.ts
  src/types/WebUrl.ts
  src/types/index.ts
Labels: bug, refactoring

#185 Refactor NewsItem and extract ImageSection/MediaSection from items
  src/components/ImageSection.js
  src/components/MediaSection.js
  src/components/StorySection.js
  src/components/index.js
  src/components/screens/EventRecord.js
  src/components/screens/NewsItem.js
  src/components/screens/PointOfInterest.js
  src/components/screens/Tour.js
Labels: refactoring

#199 fix(story section): error in logic to display body
  src/components/StorySection.js
Labels: bug

#201 feat(image): add refresh interval
  src/components/Image.js
  src/components/ImagesCarousel.js
  src/components/ImagesCarouselItem.js
  src/hooks/TimeHooks.ts
  src/hooks/index.js
Labels: enhancement

#193 fix(text): removed required flag from prop
  src/components/Text.js
Labels: bug

#194 feat(weather): pull to refresh
  src/config/texts.js
  src/screens/WeatherScreen.js
Labels: enhancement

#202 fix(address): hide empty address
  src/components/infoCard/AddressSection.tsx
Labels: enhancement
