Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2021-06, with the labels that each got.

#236 Survey: Detail (first layout) and Overview
  src/config/texts.js
  src/helpers/index.js
  src/helpers/surveyHelper.tsx
  src/hooks/index.js
  src/hooks/pullToRefetch.tsx
  src/hooks/surveyHooks.ts
  src/navigation/AppStackNavigator.js
  src/queries/survey.js
  src/screens/SurveyDetailScreen.tsx
  src/screens/SurveyOverviewScreen.tsx
  src/screens/index.js
  src/types/Survey.ts
  src/types/index.ts
Labels: enhancement

#241 Survey: Archived Survey Logic
  src/components/Results.tsx
  src/components/SurveyAnswer.tsx
  src/screens/SurveyDetailScreen.tsx
  src/screens/SurveyOverviewScreen.tsx
Labels: enhancement

#243 fix(construction site): missing default screen title
  src/navigation/AppStackNavigator.js
Labels: bug

#245 fix(drawer content): undefined key values for list
  src/navigation/DrawerNavigatorItems.js
Labels: bug

#235 Refactor: bb-bus detail
  src/components/BB-BUS/Authority.js
  src/components/BB-BUS/Block.js
  src/components/BB-BUS/Persons.js
  src/components/BB-BUS/TextBlock.js
  src/components/BB-BUS/helpers.js
  src/screens/BB-BUS/DetailScreen.js
Labels: bug, enhancement, refactoring

#242 chore(expo sdk): upgrade to 41
  package.json
  src/helpers/linkHelper.js
  src/helpers/storageHelper.js
  src/index.js
  src/pushNotifications/PermissionHandling.ts
  tsconfig.json
  yarn.lock
Labels: dependencies

#246 fix(home screen): navigation titles
  src/screens/HomeScreen.js
Labels: bug, enhancement

#247 BB-Bus: person block title
  src/components/BB-BUS/Persons.js
Labels: bug

#248 refactor(service tiles): duplicated code
  src/components/screens/ServiceTiles.js
  src/components/screens/index.js
  src/screens/CompanyScreen.js
  src/screens/ServiceScreen.js
Labels: enhancement

#214 Snapshot tests with Jest
  __tests__/App.test.js
  __tests__/__snapshots__/App.test.js.snap
  __tests__/components/Button.test.js
  __tests__/components/Icon.test.js
  __tests__/components/Link.test.js
  __tests__/components/Wrapper.test.js
  __tests__/components/__snapshots__/Button.test.js.snap
  __tests__/components/__snapshots__/Icon.test.js.snap
  __tests__/components/__snapshots__/Link.test.js.snap
  __tests__/components/__snapshots__/Wrapper.test.js.snap
  __tests__/dummyData/GenericItemDummyData.js
  __tests__/navigation/AppStackNavigator.test.js
  __tests__/navigation/CustomDrawerContentComponent.test.js
  __tests__/navigation/__snapshots__/AppStackNavigator.test.js.snap
  __tests__/navigation/__snapshots__/CustomDrawerContentComponent.test.js.snap
  __tests__/screens/DetailScreen.test.js
  __tests__/screens/HomeScreen.test.js
  __tests__/screens/HtmlScreen.test.js
  __tests__/screens/IndexScreen.test.js
  __tests__/screens/__snapshots__/DetailScreen.test.js.snap
  __tests__/screens/__snapshots__/HtmlScreen.test.js.snap
  __tests__/screens/__snapshots__/IndexScreen.test.js.snap
  jest-setup.js
  package.json
  src/SettingsProvider.js
  src/components/screens/OpeningTimesCard.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#252 Fix: header left showing on initial screens
  src/components/HeaderLeft.tsx
Labels: bug
