Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2021-04, with the labels that each got.

#217 fix image not displaying up to date image
  src/components/Image.js
  src/hooks/TimeHooks.ts
Labels: bug, enhancement

#215 fix(useMatomoTrackScreenView): correct context for matomo tracking
  src/hooks/matomoHooks.js
Labels: bug

#213 chore(pr template): added basic testing reminders
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#218 chore(offer): replace provider name with logo
  src/components/Offer.js
  src/queries/genericItem.js
Labels: enhancement
