Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-07, with the labels that each got.

#556 feat(service tiles): new option for bigger tiles
  src/components/Image.js
  src/components/ServiceBox.js
  src/components/screens/Service.js
  src/components/screens/ServiceTile.tsx
  src/components/screens/ServiceTiles.js
  src/components/screens/index.js
Labels: enhancement

#572 chore(expo sdk): upgrade to 44
  .nvmrc
  .yvmrc
  App.js
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/de/dev/smartvillage/app/MainActivity.java
  android/app/src/main/java/de/dev/smartvillage/app/MainApplication.java
  android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable/splashscreen.xml
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/sentry.properties
  babel.config.js
  eas.json
  index.js
  ios/Podfile
  ios/Podfile.lock
  ios/SmartVillageApp.xcodeproj/project.pbxproj
  ios/SmartVillageApp/AppDelegate.m
  ios/SmartVillageApp/Images.xcassets/SplashScreen.imageset/image.png
  ios/SmartVillageApp/SmartVillageApp-Bridging-Header.h
  ios/SmartVillageApp/SmartVillageApp.entitlements
  ios/SmartVillageApp/SplashScreen.storyboard
  jest-setup.js
  package.json
  yarn.lock
Labels: enhancement, dependencies

#575 chore(expo sdk): upgrade to 45
  __tests__/components/__snapshots__/Button.test.js.snap
  __tests__/components/__snapshots__/Link.test.js.snap
  android/.gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/de/dev/smartvillage/app/MainActivity.java
  android/app/src/main/java/de/dev/smartvillage/app/MainApplication.java
  android/app/src/main/java/de/dev/smartvillage/app/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/de/dev/smartvillage/app/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/de/dev/smartvillage/app/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  app.json
  ios/.gitignore
  ios/Podfile
  ios/Podfile.lock
  ios/SmartVillageApp.xcodeproj/project.pbxproj
  ios/SmartVillageApp/AppDelegate.m
  ios/SmartVillageApp/AppDelegate.mm
  ios/SmartVillageApp/Info.plist
  ios/SmartVillageApp/SmartVillageApp-Bridging-Header.h
  ios/sentry.properties
  package.json
  src/config/navigation/config.ts
  yarn.lock
Labels: enhancement, dependencies

#578 feat(ar): start animation
  src/screens/augmentedReality/ARShowScreen.js
Labels: enhancement, ar

#577 feat(ar): record screen
  src/components/augmentedReality/AugmentedReality.js
  src/components/screens/Tour.js
  src/config/texts.js
  src/screens/SettingsScreen.js
  src/screens/augmentedReality/ARShowScreen.js
Labels: enhancement, ar

#571 feat(ar): show ar model
  src/components/augmentedReality/ARObjectList.js
  src/components/augmentedReality/ARObjectListItem.js
  src/components/augmentedReality/AugmentedReality.js
  src/components/augmentedReality/WhatIsARButton.js
  src/components/augmentedReality/index.js
  src/components/screens/Tour.js
  src/config/texts.js
  src/screens/SettingsScreen.js
  src/screens/augmentedReality/ARShowScreen.js
  src/screens/augmentedReality/ArtworkDetailScreen.js
Labels: enhancement, ar

#570 feat(ar object): parse ar object
  src/components/augmentedReality/ARObjectList.js
  src/components/augmentedReality/ARObjectListItem.js
  src/components/augmentedReality/AugmentedReality.js
  src/components/augmentedReality/WhatIsARButton.js
  src/components/augmentedReality/index.js
  src/components/screens/Tour.js
  src/config/texts.js
  src/screens/SettingsScreen.js
  src/screens/augmentedReality/ARShowScreen.js
  src/screens/augmentedReality/ArtworkDetailScreen.js
Labels: enhancement, ar

#569 fix(storage name): change directory
  src/components/augmentedReality/ARObjectList.js
  src/components/augmentedReality/ARObjectListItem.js
  src/components/augmentedReality/AugmentedReality.js
  src/components/augmentedReality/WhatIsARButton.js
  src/components/augmentedReality/index.js
  src/components/screens/Tour.js
  src/config/texts.js
  src/helpers/augmentedReality/checkDownloadedData.js
  src/helpers/augmentedReality/deleteObject.js
  src/helpers/augmentedReality/downloadAndDeleteAllData.js
  src/helpers/augmentedReality/downloadObject.js
  src/helpers/augmentedReality/storageNameCreator.js
  src/screens/SettingsScreen.js
  src/screens/augmentedReality/ARShowScreen.js
  src/screens/augmentedReality/ArtworkDetailScreen.js
Labels: bug, ar

#581 fix: react types version and versions listed in README
  README.md
  package.json
  yarn.lock
Labels: bug

#580 fix: query variables without limit
  src/screens/IndexScreen.js
Labels: bug

#586 feat(ar): add viro sound
  src/screens/augmentedReality/ARShowScreen.js
Labels: enhancement, ar

#584 refactor(ar): delete object move and rotate functions
  src/screens/augmentedReality/ARShowScreen.js
Labels: refactoring, ar

#583 fix: solve empty section error
  src/components/CrossData.tsx
  src/components/DataListSection.tsx
Labels: bug

#589 refactor(consul): save user id
  src/components/screens/consul/Debates/DebateDetail.js
  src/components/screens/consul/Polls/PollDetail.js
  src/components/screens/consul/Proposals/ProposalDetail.js
  src/components/screens/consul/UserComments/UserCommentDetail.js
  src/helpers/consul/index.js
  src/screens/consul/ConsulHomeScreen.js
  src/screens/consul/LoginRegister/ConsulLoginScreen.js
Labels: enhancement, refactoring, consul

#590 feat(ar): show buttons after loading the 3D object
  src/config/texts.js
  src/screens/augmentedReality/ARShowScreen.js
Labels: enhancement, ar

#593 feat(ar): support device according to version
  src/components/augmentedReality/AugmentedReality.js
  src/screens/SettingsScreen.js
Labels: enhancement, ar

#595 feat(news): index with multiple category ids
  src/hooks/NewsCategories.ts
  src/queries/newsItems.js
  src/screens/HomeScreen.js
Labels: enhancement

#592 feat(ar): recognise image and show model
  src/components/augmentedReality/AugmentedReality.js
  src/components/augmentedReality/AugmentedRealityView.js
  src/components/augmentedReality/index.js
  src/config/texts.js
  src/screens/SettingsScreen.js
  src/screens/augmentedReality/ARShowScreen.js
Labels: enhancement, ar

#597 chore: new icon and splash screen for development
  assets/icon.png
  assets/splash.png
Labels: enhancement, refactoring

#596 chore(android): use hermes as js engine
  app.json
  assets/icon.png
  assets/splash.png
  metro.config.js
  package.json
  src/helpers/colorHelper.ts
  yarn.lock
Labels: enhancement, refactoring

#598 fix(ar): solve android crash for recognise image
  src/components/augmentedReality/AugmentedRealityView.js
Labels: bug, ar
