Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-11, with the labels that each got.

#677 feat(volunteer): new home screen
  src/components/Button.js
  src/components/screens/ServiceTiles.js
  src/config/colors.js
  src/hooks/HomeRefresh.ts
  src/queries/types.ts
  src/screens/volunteer/VolunteerHomeScreen.tsx
Labels: enhancement, volunteer

#678 feat(volunteer): new personal screen
  src/config/navigation/defaultStackConfig.tsx
  src/hooks/HomeRefresh.ts
  src/navigation/screenOptions.tsx
  src/queries/types.ts
  src/screens/volunteer/VolunteerLogoutScreen.tsx
  src/screens/volunteer/VolunteerPersonalScreen.tsx
  src/screens/volunteer/index.ts
  src/types/Navigation.ts
Labels: enhancement, volunteer

#679 chore(volunteer): remove unused code
  src/components/volunteer/VolunteerHeader.tsx
  src/components/volunteer/VolunteerTask.js
  src/components/volunteer/VolunteerUser.tsx
  src/components/volunteer/VolunteerWelcome.tsx
  src/components/volunteer/index.ts
  src/config/Icon.tsx
  src/helpers/parser/listItemParser.js
  src/helpers/parser/volunteer/additionalData.js
  src/helpers/parser/volunteer/index.ts
  src/helpers/parser/volunteer/profileData.js
  src/helpers/parser/volunteer/tasksData.js
  src/helpers/queryHelper.ts
  src/helpers/shareHelper.js
  src/hooks/listHooks.js
  src/hooks/volunteer/data.ts
  src/hooks/volunteer/user.tsx
  src/queries/volunteer/auth.ts
  src/screens/volunteer/VolunteerDetailScreen.tsx
  src/screens/volunteer/VolunteerHomeScreen.tsx
  src/screens/volunteer/VolunteerIndexScreen.tsx
Labels: refactoring, volunteer

#680 feat(volunteer): update login register
  src/components/Title.js
  src/components/screens/PointOfInterest.js
  src/components/screens/consul/Proposals/ProposalDetail.js
  src/components/volunteer/VolunteerGroup.tsx
  src/components/volunteer/VolunteerUser.tsx
  src/screens/ConstructionSiteDetailScreen.js
  src/screens/consul/LoginRegister/ConsulLoginScreen.js
  src/screens/consul/LoginRegister/ConsulRegisterScreen.js
  src/screens/volunteer/VolunteerLoginScreen.tsx
  src/screens/volunteer/VolunteerRegisteredScreen.tsx
  src/screens/volunteer/VolunteerRegistrationScreen.tsx
  src/screens/volunteer/VolunteerSignupScreen.tsx
Labels: refactoring, volunteer

#685 feat(volunteer): update the icon of the scroll down button
  src/components/Chat.js
Labels: enhancement, volunteer

#676 feature(volunteer): redirect unregistered users to `VolunteerHomeScreen`
  src/components/volunteer/VolunteerGroup.tsx
  src/hooks/volunteer/user.tsx
Labels: enhancement, volunteer

#687 refactor: change wording on the data source filter
  src/config/texts.js
Labels: refactoring

#681 feat(volunteer): navigate from personal to login if not logged in
  src/screens/volunteer/VolunteerPersonalScreen.tsx
Labels: enhancement, volunteer

#682 feat(volunteer): update index screens
  src/components/CategoryListItem.js
  src/components/TextListItem.tsx
  src/components/consul/list/ConsulListItem.js
  src/components/oParl/previews/OParlPreviewEntry.tsx
  src/components/volunteer/VolunteerConversationListItem.tsx
  src/components/volunteer/VolunteerHomeSection.tsx
  src/config/Icon.tsx
  src/config/texts.js
  src/helpers/parser/listItemParser.js
  src/icons/index.js
  src/icons/list.js
  src/icons/member.js
  src/icons/volunteerCalendar.js
  src/screens/volunteer/VolunteerIndexScreen.tsx
Labels: enhancement, volunteer

#684 refactor(volunteer): delete `UserAvatar` component
  src/components/Chat.js
  src/components/volunteer/VolunteerAvatar.tsx
  src/components/volunteer/VolunteerMessage.tsx
Labels: refactoring, volunteer

#683 feat(volunteer): add visibility and `joinPolicy` to create a group
  src/components/volunteer/VolunteerFormGroup.tsx
  src/config/texts.js
  src/queries/volunteer/group.ts
Labels: enhancement, volunteer

#688 fix(volunteer): fix avatar not appearing in event attendee list
  src/helpers/parser/listItemParser.js
Labels: bug, volunteer

#689 fix(volunteer): tablet profile
  src/components/volunteer/VolunteerUser.tsx
Labels: bug, volunteer

#690 refactor: rendering when present
  src/components/ListComponent.js
  src/components/screens/About.js
Labels: refactoring

#691 fix(volunteer): event creation
  src/components/ListComponent.js
  src/components/screens/About.js
  src/components/volunteer/VolunteerEventRecord.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
Labels: bug, volunteer

#693 fix(ar): android error due to `ViroAmbientLight`
  src/components/augmentedReality/AugmentedRealityView.js
Labels: bug, ar

#694 refactor: adjust `normalize` import
  src/components/CommentSection.tsx
  src/components/Radiobutton.js
  src/components/map/Map.tsx
  src/components/screens/ServiceTile.tsx
  src/components/screens/ServiceTiles.js
  src/components/survey/SurveyAnswer.tsx
  src/components/volunteer/VolunteerHomeSection.tsx
  src/components/wasteCalendar/WasteReminderSettings.tsx
  src/screens/EncounterDataScreen.tsx
  src/screens/EncounterRegistrationScreen.tsx
Labels: refactoring

#701 feat(price card): show 'kostenlos' instead of nothing
  src/components/screens/PriceCard.js
  src/config/texts.js
  src/helpers/priceHelper.js
Labels: enhancement

#698 feat(noticeboard): add `noticeboardIndexScreen`
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/screens/NestedInfoScreen.tsx
  src/screens/NoticeboardIndexScreen.tsx
  src/screens/index.js
  src/types/Navigation.ts
Labels: enhancement

#697 feat(noticeboard): add `subQuery` to `nestedInfoScreen`
  src/components/MultiButtonWithSubQuery.tsx
  src/components/index.js
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/screens/HtmlScreen.js
  src/screens/NestedInfoScreen.tsx
  src/screens/NoticeboardIndexScreen.tsx
  src/screens/index.js
  src/types/Navigation.ts
  src/types/SubQuery.ts
  src/types/index.ts
Labels: enhancement

#692 feat(push notifications): exclude data providers
  app.json
  src/components/settings/PermanentFilterSettings.tsx
  src/config/secrets.temp
  src/pushNotifications/PermissionHandling.ts
  src/pushNotifications/TokenHandling.ts
Labels: enhancement

#699 feat(personalized tiles): sorting and toggling visibility with storing on device
  src/components/HomeService.js
  src/components/index.js
  src/components/screens/DraggableGrid.tsx
  src/components/screens/DraggableItem.tsx
  src/components/screens/Service.tsx
  src/components/screens/ServiceTile.tsx
  src/components/screens/ServiceTiles.js
  src/config/Icon.tsx
  src/config/texts.js
  src/hooks/index.js
  src/hooks/personalizedTiles.ts
  src/screens/HomeScreen.js
  src/screens/HtmlScreen.js
  src/screens/TilesScreen.js
  src/screens/volunteer/VolunteerHomeScreen.tsx
  src/screens/volunteer/VolunteerPersonalScreen.tsx
Labels: enhancement

#703 feat: use data resource settings for toggling url links/buttons
  src/components/screens/EventRecord.js
  src/queries/eventRecords.js
Labels: enhancement
