Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-06, with the labels that each got.

#543 feat(bus bb): remove teaser and fix order typo
  src/screens/BB-BUS/DetailScreen.js
Labels: enhancement

#545 fix(home screen): render button for all points of interest and tours
  src/components/HomeSection.tsx
  src/screens/HomeScreen.js
Labels: bug

#525 feat(intro): repeat app intro
  src/OnboardingManager.tsx
  src/config/texts.js
  src/screens/SettingsScreen.js
Labels: enhancement

#524 fix(waste reminder): send notify_at always in winter time
  src/components/wasteCalendar/WasteReminderSettings.tsx
  src/pushNotifications/WasteReminder.ts
Labels: bug

#506 feat(bb bus): migrate to api v4
  src/BBBusClient.tsx
  src/components/BB-BUS/Authority.js
  src/components/BB-BUS/TextBlock.js
  src/components/BB-BUS/helpers.js
  src/queries/BB-BUS/getService.ts
  src/screens/BB-BUS/DetailScreen.js
  src/screens/BB-BUS/IndexScreen.js
Labels: enhancement

#555 feat(volunteer): integrate one time code in registration
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/queries/volunteer/auth.ts
  src/screens/volunteer/VolunteerLoginScreen.tsx
  src/screens/volunteer/VolunteerRegistrationScreen.tsx
  src/screens/volunteer/VolunteerSignupScreen.tsx
  src/screens/volunteer/index.ts
  src/types/Navigation.ts
  src/types/volunteer/user.ts
Labels: enhancement, volunteer

#557 fix(global settings): initializations and accesses
  src/SettingsProvider.js
  src/components/FeedbackFooter.tsx
  src/components/infoCard/AddressSection.tsx
  src/components/settings/ListSettings.js
  src/index.js
  src/screens/DetailScreen.js
  src/screens/EncounterHomeScreen.tsx
  src/screens/HomeScreen.js
  src/screens/SettingsScreen.js
Labels: bug

#558 feat: always show version number in drawer mode
  src/components/screens/About.js
Labels: enhancement

#561 refactor: conditional chaining in favor of && chained check
  src/components/volunteer/VolunteerEventRecord.tsx
  src/screens/volunteer/VolunteerLoginScreen.tsx
  src/screens/volunteer/VolunteerMeScreen.tsx
  src/screens/volunteer/VolunteerRegistrationScreen.tsx
  src/screens/volunteer/VolunteerSignupScreen.tsx
Labels: refactoring, volunteer

#562 refactor: unify mail icon
  src/components/consul/detail/ConsulCommentListItem.js
  src/components/screens/consul/Debates/DebateDetail.js
  src/components/screens/consul/Polls/PollDetail.js
  src/components/screens/consul/Proposals/ProposalDetail.js
  src/config/Icon.tsx
Labels: refactoring, consul

#560 refactor(colors): adjust and cleanup
  __tests__/components/__snapshots__/Link.test.js.snap
  __tests__/config/colors.test.js
  src/components/BB-BUS/IndexFilter.js
  src/components/Checkbox.js
  src/components/DropdownSelect.js
  src/components/Link.js
  src/components/Radiobutton.js
  src/components/Text.js
  src/components/Title.js
  src/components/consul/detail/ConsulDocumentListItem.js
  src/components/form/Input.tsx
  src/components/screens/consul/Debates/DebateDetail.js
  src/components/screens/consul/Polls/PollDetail.js
  src/components/screens/consul/Proposals/NewProposal.js
  src/components/screens/consul/Proposals/ProposalDetail.js
  src/components/volunteer/VolunteerAvatar.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/components/volunteer/VolunteerFormGroup.tsx
  src/components/volunteer/VolunteerMessage.tsx
  src/config/colors.js
  src/navigation/DrawerNavigatorItem.js
  src/screens/EncounterHomeScreen.tsx
  src/screens/FeedbackScreen.js
Labels: refactoring

#564 refactor/fix: && chained check in addition to conditional chaining
  src/screens/volunteer/VolunteerMeScreen.tsx
  src/screens/volunteer/VolunteerSignupScreen.tsx
Labels: bug, refactoring, volunteer

#551 setup eas build
  app.json
  eas.json
  index.js
  package.json
Labels: enhancement, dependencies, refactoring
