Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-10, with the labels that each got.

#655 fix(volunteer): solve `useNativeDrive` warn
  src/components/Chat.js
Labels: bug, volunteer

#660 fix(maps): make polyline visible for android
  src/components/map/Map.tsx
Labels: bug

#657 feat: add image to service page
  src/components/screens/ServiceTiles.js
  src/config/navigation/defaultStackConfig.tsx
  src/screens/TilesScreen.js
Labels: enhancement

#661 feat(ar): add `tourId` to ar object in `globalSettings`
  src/components/augmentedReality/AugmentedReality.js
  src/screens/SettingsScreen.js
Labels: enhancement, ar

#662 fix: add try catch if Viro is not integrated per app.json
  src/components/augmentedReality/AugmentedReality.js
  src/screens/SettingsScreen.js
Labels: bug, ar

#663 fix(ios): location request on map
  src/components/map/Map.tsx
Labels: bug

#664 fix: coords in location settings
  src/components/map/Map.tsx
  src/components/settings/LocationSettings.js
Labels: bug

#659 docs(ar): add documents for ar
  docs/AR.md
  docs/INDEX.md
  docs/assets/ModelUpload/ModelUpload0.png
  docs/assets/ModelUpload/ModelUpload1.png
  docs/assets/ModelUpload/ModelUpload2.png
  docs/assets/ModelUpload/ModelUpload3.png
  docs/assets/ModelUpload/ModelUpload4.png
  docs/assets/ModelUpload/ModelUpload5.png
  docs/assets/ModelUpload/ModelUpload6.png
  docs/assets/ModelUpload/ModelUpload7.png
  docs/assets/ModelUpload/ModelUpload8.png
  docs/assets/ModelUpload/thumb.png
  docs/assets/VRXConverter/VRXConverter1.png
  docs/assets/VRXConverter/VRXConverter2.png
  docs/assets/VRXConverter/VRXConverter3.png
  docs/assets/VRXConverter/VRXConverter4.png
  docs/assets/VRXConverter/thumb.png
Labels: ar

#665 feat: add parameter to useEffect
  src/screens/SettingsScreen.js
Labels: enhancement

#667 feat(ar): multiple model management
  src/helpers/augmentedReality/checkDownloadedData.js
  src/helpers/augmentedReality/deleteObject.js
  src/helpers/augmentedReality/downloadAndDeleteAllData.js
  src/helpers/augmentedReality/downloadObject.js
  src/helpers/augmentedReality/storageNameCreator.js
  src/screens/augmentedReality/ARShowScreen.js
Labels: enhancement, ar

#671 feat(ar): add physical width value in global settings
  src/components/augmentedReality/AugmentedRealityView.js
Labels: enhancement, ar

#670 feat(ar): add format size for augmented reality
  src/components/augmentedReality/ARObjectList.js
  src/helpers/augmentedReality/progressSizeGenerator.js
  src/helpers/fileSizeHelper.ts
Labels: enhancement, ar

#672 feat(ar): remove description on map page
  src/screens/MapViewScreen.js
Labels: enhancement, ar

#674 feat(ar): add light props for viro ambient light
  src/components/augmentedReality/AugmentedRealityView.js
  src/helpers/augmentedReality/deleteObject.js
  src/helpers/augmentedReality/downloadObject.js
  src/screens/augmentedReality/ARShowScreen.js
Labels: enhancement, ar

#669 feat(ar): add description to artwork detail page
  src/screens/augmentedReality/ArtworkDetailScreen.js
Labels: enhancement, ar

#673 feat(volunteer): send messages to group admins
  src/components/volunteer/VolunteerGroup.tsx
  src/config/texts.js
  src/types/volunteer/group.ts
Labels: enhancement, volunteer

#675 docs(ar): update document with light prop
  docs/AR.md
  docs/assets/ModelUpload/ModelUpload7.png
  docs/assets/ModelUpload/ModelUpload9.png
Labels: ar

#624 feature(volunteer): editing of calendar data
  src/components/Button.js
  src/components/consul/selectors/DocumentSelector.js
  src/components/consul/selectors/ImageSelector.js
  src/components/form/DropdownInput.tsx
  src/components/form/Input.tsx
  src/components/volunteer/VolunteerEventRecord.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/config/texts.js
  src/queries/volunteer/calendar.ts
  src/queries/volunteer/calendarUpload.ts
  src/screens/volunteer/VolunteerFormScreen.tsx
  src/types/volunteer/calendar.ts
Labels: enhancement, volunteer
