Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-08, with the labels that each got.

#599 feat: add filter for daily events on index screen
  src/components/CategoryList.js
  src/components/DropdownHeader.js
  src/components/DropdownSelect.js
  src/components/EventList.js
  src/components/VerticalList.js
  src/components/widgets/EventWidget.tsx
  src/config/texts.js
  src/queries/newsItems.js
  src/screens/IndexScreen.js
Labels: enhancement

#600 feat(map): add on settings screen new map
  src/components/map/Map.tsx
  src/components/settings/LocationSettings.js
Labels: enhancement

#601 feat(map): add on location component new map
  src/components/map/Map.tsx
  src/components/oParl/Location.tsx
Labels: enhancement

#602 feat(map): add on `POI` new map
  src/components/screens/PointOfInterest.js
Labels: enhancement

#603 feat(map): add on proposal detail screen new map
  src/components/screens/consul/Proposals/ProposalDetail.js
Labels: enhancement

#604 feat(map): add on `ConstructionSiteDetailScreen` new map
  src/screens/ConstructionSiteDetailScreen.js
Labels: enhancement

#607 fix(linking): error android linking not opening
  src/helpers/linkHelper.js
Labels: bug

#610 refactor(volunteer): rename "Gruppen" to "Gruppen und Vereine"
  src/components/volunteer/VolunteerFormGroup.tsx
  src/config/texts.js
  src/helpers/parser/volunteer/additionalData.js
  src/screens/volunteer/VolunteerHomeScreen.tsx
  src/screens/volunteer/VolunteerPersonalScreen.tsx
Labels: refactoring, volunteer

#609 feat(volunteer): add group membership requests
  src/components/Button.js
  src/components/ListComponent.js
  src/components/TextListItem.tsx
  src/components/VerticalList.js
  src/components/volunteer/VolunteerApplicantListItem.tsx
  src/components/volunteer/VolunteerGroup.tsx
  src/components/volunteer/VolunteerGroupMember.tsx
  src/components/volunteer/VolunteerGroupMembersAndApplicants.tsx
  src/components/volunteer/index.ts
  src/config/texts.js
  src/helpers/parser/listItemParser.js
  src/helpers/volunteerHelper.ts
  src/hooks/listHooks.js
  src/hooks/volunteer/data.ts
  src/queries/index.js
  src/queries/types.ts
  src/queries/volunteer/group.ts
  src/screens/volunteer/VolunteerIndexScreen.tsx
  src/types/volunteer/group.ts
Labels: enhancement, volunteer

#612 feat(volunteer): update route for user requests with id
  src/queries/volunteer/user.ts
Labels: refactoring, volunteer

#614 feat: multi button screen with html
  src/screens/MultiButtonScreen.tsx
Labels: enhancement

#613 feat(volunteer): hdvt events between main server events
  src/SettingsProvider.js
  src/components/DataListSection.tsx
  src/components/HomeSection.tsx
  src/components/volunteer/VolunteerEventRecord.tsx
  src/components/widgets/EventWidget.tsx
  src/config/texts.js
  src/helpers/parser/listItemParser.js
  src/hooks/volunteer/data.ts
  src/index.js
  src/queries/volunteer/calendar.ts
  src/screens/HomeScreen.js
  src/screens/IndexScreen.js
  src/screens/volunteer/VolunteerIndexScreen.tsx
Labels: enhancement, volunteer

#606 feat(volunteer): upload image and document for calendar
  src/components/consul/selectors/DocumentSelector.js
  src/components/consul/selectors/ImageSelector.js
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/config/texts.js
  src/helpers/index.js
  src/helpers/jsonParser.ts
  src/queries/volunteer/calendarUpload.ts
  src/queries/volunteer/index.ts
  src/types/volunteer/calendar.ts
Labels: enhancement, volunteer

#615 feat(volunteer): render documents for volunteer events
  src/components/volunteer/VolunteerEventRecord.tsx
  src/config/Icon.tsx
Labels: enhancement, volunteer

#608 feat(ar): add `tourStops` query
  src/components/augmentedReality/ARModal.js
  src/components/augmentedReality/ARObjectList.js
  src/components/augmentedReality/ARObjectListItem.js
  src/components/augmentedReality/AugmentedReality.js
  src/components/augmentedReality/AugmentedRealityView.js
  src/components/augmentedReality/IconForDownloadType.js
  src/components/screens/Tour.js
  src/helpers/augmentedReality/checkDownloadedData.js
  src/helpers/augmentedReality/deleteObject.js
  src/helpers/augmentedReality/downloadAndDeleteAllData.js
  src/helpers/augmentedReality/downloadObject.js
  src/helpers/augmentedReality/storageNameCreator.js
  src/queries/index.js
  src/queries/tours.js
  src/queries/types.ts
  src/screens/SettingsScreen.js
  src/screens/augmentedReality/ARShowScreen.js
  src/screens/augmentedReality/ArtworkDetailScreen.js
Labels: enhancement, ar

#617 fix: solve cycle warn
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/hooks/listHooks.js
Labels: bug

#616 fix(ar): delete screen recording function
  src/screens/augmentedReality/ARShowScreen.js
Labels: bug, ar

#618 feat(maps): `react-native-maps` instead of `react-native-webview-leaflet`
  app.json
  package.json
  src/components/augmentedReality/AugmentedReality.js
  src/components/map/LocationOverview.tsx
  src/components/map/Map.tsx
  src/components/map/WebViewMap.tsx
  src/components/map/index.ts
  src/components/oParl/Location.tsx
  src/components/screens/PointOfInterest.js
  src/components/screens/consul/Proposals/ProposalDetail.js
  src/components/settings/LocationSettings.js
  src/screens/ConstructionSiteDetailScreen.js
  src/screens/SettingsScreen.js
  src/types/Map.ts
  src/types/index.ts
  yarn.lock
Labels: enhancement, dependencies, refactoring

#620 feat(volunteer): list all my groups
  src/components/TextListItem.tsx
  src/components/volunteer/VolunteerGroup.tsx
  src/components/volunteer/VolunteerHomeSection.tsx
  src/config/texts.js
  src/helpers/parser/listItemParser.js
  src/helpers/volunteerHelper.ts
  src/hooks/volunteer/data.ts
  src/queries/index.js
  src/queries/volunteer/calendar.ts
  src/queries/volunteer/group.ts
  src/screens/volunteer/VolunteerPersonalScreen.tsx
Labels: enhancement, refactoring, volunteer
