Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-09, with the labels that each got.

#621 feature(event): not showing count in event widget
  src/components/widgets/DefaultWidget.tsx
  src/components/widgets/EventWidget.tsx
  src/types/WidgetProps.ts
Labels: enhancement

#623 feat(encounter): deactivate after pressing the save button
  src/screens/EncounterDataScreen.tsx
Labels: enhancement

#622 fix: solve error to `Autocomplete` package
  src/screens/WasteCollectionScreen.js
Labels: bug

#630 fix: event widget initial list data
  src/components/widgets/EventWidget.tsx
Labels: bug

#631 feat(widget): add new water temperature widget
  src/components/widgets/WaterTemperatureWidget.tsx
  src/components/widgets/Widgets.tsx
  src/config/texts.js
  src/hooks/index.js
  src/hooks/waterTemperature.ts
  src/queries/types.ts
  src/queries/waterTemperature.js
  src/types/WidgetProps.ts
Labels: enhancement

#632 feat(volunteer): adjustments after extension 0.5
  src/components/volunteer/VolunteerCalendar.tsx
  src/components/volunteer/VolunteerEventAttending.tsx
  src/components/volunteer/VolunteerEventRecord.tsx
  src/components/volunteer/VolunteerGroup.tsx
  src/components/volunteer/VolunteerGroupMembersAndApplicants.tsx
  src/components/volunteer/VolunteerHeader.tsx
  src/components/volunteer/VolunteerHomeSection.tsx
  src/components/volunteer/VolunteerMessageTextField.tsx
  src/components/volunteer/VolunteerPosts.tsx
  src/config/texts.js
  src/helpers/parser/listItemParser.js
  src/helpers/parser/volunteer/calendarData.js
  src/helpers/parser/volunteer/groupsData.js
  src/helpers/parser/volunteer/index.ts
  src/helpers/parser/volunteer/messagesData.js
  src/helpers/volunteerHelper.ts
  src/hooks/volunteer/data.ts
  src/queries/volunteer/calendar.ts
  src/queries/volunteer/conversation.ts
  src/queries/volunteer/group.ts
  src/queries/volunteer/post.ts
  src/queries/volunteer/upload.ts
  src/queries/volunteer/user.ts
  src/screens/volunteer/VolunteerDetailScreen.tsx
  src/screens/volunteer/VolunteerIndexScreen.tsx
  src/screens/volunteer/VolunteerPersonalScreen.tsx
Labels: bug, enhancement, volunteer

#611 feat(volunteer): add gifted chat
  package.json
  src/components/Chat.js
  src/components/index.js
  src/components/volunteer/VolunteerConversationsSection.tsx
  src/components/volunteer/VolunteerMessage.tsx
  src/helpers/parser/listItemParser.js
  src/screens/volunteer/VolunteerDetailScreen.tsx
  src/screens/volunteer/VolunteerPersonalScreen.tsx
Labels: enhancement, volunteer

#626 feature(volunteer): editing of personal data
  src/components/form/DropdownInput.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/components/volunteer/VolunteerFormGroup.tsx
  src/components/volunteer/VolunteerFormProfile.tsx
  src/components/volunteer/VolunteerUser.tsx
  src/components/volunteer/index.ts
  src/config/texts.js
  src/queries/volunteer/user.ts
  src/screens/volunteer/VolunteerFormScreen.tsx
  src/types/volunteer/country.ts
  src/types/volunteer/index.ts
  src/types/volunteer/user.ts
Labels: enhancement, volunteer

#633 Fixes for volunteer version after 3.0.0 merge
  src/components/Chat.js
  src/components/DataListSection.tsx
  src/components/volunteer/VolunteerCalendar.tsx
  src/components/volunteer/VolunteerConversationsSection.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/components/volunteer/VolunteerGroup.tsx
  src/components/volunteer/VolunteerHomeSection.tsx
  src/helpers/parser/listItemParser.js
  src/screens/volunteer/VolunteerHomeScreen.tsx
  src/screens/volunteer/VolunteerMeScreen.tsx
  src/screens/volunteer/VolunteerPersonalScreen.tsx
Labels: bug, volunteer

#619 feat(maps): add polyline to map
  src/components/augmentedReality/AugmentedReality.js
  src/components/map/Map.tsx
  src/components/screens/Tour.js
  src/queries/tours.js
  src/screens/MapViewScreen.js
Labels: enhancement, ar

#637 refactor(bus bb): build apollo client with uri from global settings
  src/BBBusClient.tsx
  src/config/secrets.temp
  src/hooks/apollo.ts
  src/screens/BB-BUS/DetailScreen.js
  src/screens/BB-BUS/IndexScreen.js
Labels: enhancement, refactoring

#638 feat: move configs from secrets to global settings
  src/CustomMatomoProvider.js
  src/OParlClient.tsx
  src/config/secrets.temp
  src/hooks/apollo.ts
  src/hooks/waterTemperature.ts
  src/queries/waterTemperature.js
  src/screens/OParl/OParlOrganisationsScreen.tsx
Labels: enhancement, refactoring

#636 refactor(volunteer): change the language of the country object
  src/components/volunteer/VolunteerFormProfile.tsx
  src/types/volunteer/countries.ts
  src/types/volunteer/country.ts
  src/types/volunteer/index.ts
Labels: refactoring, volunteer

#639 refactor(icons): all icons in config
  src/components/Chat.js
  src/config/Icon.tsx
  src/screens/augmentedReality/ARShowScreen.js
Labels: refactoring

#635 feat(encounter): add expo barcode scanner
  package.json
  src/screens/EncounterScannerScreen.tsx
  yarn.lock
Labels: enhancement

#640 fix(map): fix map on settings screen
  src/components/settings/LocationSettings.js
Labels: bug

#641 refactor: change places inside the gitignore
  .gitignore
Labels: refactoring

#643 refactor(map): relocate
  src/components/settings/LocationSettings.js
Labels: refactoring

#649 fix(viro): remove plugin integration by default
  app.json
Labels: bug, ar

#642 style(volunteer): change text input and media preview style
  src/components/Chat.js
Labels: refactoring, volunteer

#634 feat(ar): add new server requests, spatial sound, video and image components
  src/components/augmentedReality/AugmentedRealityView.js
  src/helpers/augmentedReality/downloadObject.js
  src/screens/augmentedReality/ARShowScreen.js
Labels: enhancement, ar
