Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-01, with the labels that each got.

#427 feat(categories): filter by ids
  src/queries/categories.js
Labels: enhancement

#416 fix(location service): missing android permissions
  app.json
Labels: bug

#414 Chore: unify top filters
  src/components/BB-BUS/IndexFilter.js
  src/components/IndexFilterElement.js
  src/components/IndexFilterWrapperAndList.js
  src/components/MapSwitchHeader.tsx
  src/components/index.js
  src/config/texts.js
  src/screens/BB-BUS/IndexScreen.js
  src/screens/IndexScreen.js
  src/screens/SettingsScreen.js
Labels: enhancement

#425 Feature: multi button screen
  src/config/navigation/defaultStackConfig.tsx
  src/queries/categories.js
  src/screens/MultiButtonScreen.tsx
  src/screens/index.js
  src/types/Navigation.ts
Labels: enhancement

#417 Fix: location overview ignoring opening times filter
  src/components/map/LocationOverview.tsx
  src/screens/IndexScreen.js
Labels: bug

#426 setup: sentry
  App.js
  app.config.js
  app.json
  package.json
  src/config/secrets.temp
  yarn.lock
Labels: enhancement

#431 fix(sentry): setup with expo
  App.js
Labels: bug

#429 Fix: photo permission bug
  src/components/Image.js
Labels: bug, enhancement, refactoring

#419 Feature: replace directus by new bb bus api
  package.json
  src/BBBusClient.tsx
  src/components/BB-BUS/IndexFilter.js
  src/components/BB-BUS/Persons.js
  src/components/BB-BUS/ServiceList.js
  src/components/BB-BUS/TextBlock.js
  src/components/BB-BUS/helpers.js
  src/config/consts.js
  src/hooks/apollo.ts
  src/queries/BB-BUS/directus.js
  src/queries/BB-BUS/getAreasAndTop10.ts
  src/queries/BB-BUS/getService.ts
  src/queries/BB-BUS/getServices.ts
  src/queries/BB-BUS/getTop10Ids.js
  src/queries/BB-BUS/index.ts
  src/screens/BB-BUS/DetailScreen.js
  src/screens/BB-BUS/IndexScreen.js
  yarn.lock
Labels: enhancement

#438 fix(sentry): moved sentry config to another position in the secrets t…
  App.js
  app.config.js
  src/config/secrets.temp
Labels: refactoring
