Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-12, with the labels that each got.

#704 feat(ar): make the sound infinite loop
  src/components/augmentedReality/AugmentedRealityView.js
Labels: enhancement, ar

#706 feature(ar): show multiple models in one scene
  src/components/augmentedReality/AugmentedRealityView.js
  src/helpers/augmentedReality/multipleSceneIndexGenerator.ts
  src/helpers/augmentedReality/objectParser.js
Labels: enhancement, ar

#707 feat(deadline): add content rendering for index and detail and toggle push device assignment
  src/components/CrossData.tsx
  src/components/Offer.js
  src/components/bookmarks/BookmarkHeader.tsx
  src/config/consts.js
  src/config/texts.js
  src/helpers/genericTypeHelper.ts
  src/helpers/parser/listItemParser.js
  src/pushNotifications/TokenHandling.ts
  src/queries/genericItem.js
  src/screens/BookmarkScreen.js
  src/screens/DetailScreen.js
  src/types/GenericType.ts
Labels: enhancement

#708 refactor(noticeboard): add `consentForDataProcessingText` to `listItem`
  src/helpers/parser/listItemParser.js
  src/screens/Noticeboard/NoticeboardIndexScreen.tsx
Labels: refactoring

#709 feat(defect report): new form with image upload
  src/components/consul/selectors/ImageSelector.js
  src/components/defectReport/DefectReportCreateForm.tsx
  src/components/defectReport/DefectReportLocationForm.tsx
  src/components/defectReport/index.ts
  src/components/index.js
  src/components/noticeboard/NoticeboardMessageForm.tsx
  src/components/screens/consul/Proposals/NewProposal.js
  src/components/settings/LocationSettings.js
  src/config/consts.js
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/helpers/genericTypeHelper.ts
  src/hooks/locationHooks.ts
  src/queries/genericItem.js
  src/queries/mediaContent.js
  src/screens/DefectReport/DefectReportFormScreen.tsx
  src/screens/DefectReport/index.ts
  src/screens/DetailScreen.js
  src/screens/index.js
  src/types/GenericType.ts
  src/types/Navigation.ts
Labels: enhancement

#710 fix(static contents): add error if not an object
  src/components/screens/Service.tsx
  src/components/screens/ServiceTiles.js
  src/hooks/staticContent.ts
Labels: bug

#711 feat(deadlines): show category in list
  src/helpers/genericTypeHelper.ts
  src/helpers/parser/listItemParser.js
Labels: enhancement

#712 fix(ar): add height to modal
  src/components/Modal.js
  src/components/augmentedReality/ARModal.js
Labels: bug, ar

#713 fix(ar): click on map marker issue fixed
  src/components/augmentedReality/AugmentedReality.js
  src/helpers/augmentedReality/multipleSceneIndexGenerator.ts
Labels: bug, ar
