Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2022-02, with the labels that each got.

#441 fix(leaflet-crash): switch to another fork
  package.json
  yarn.lock
Labels: bug

#418 Feature: versioned static contents
  src/components/ConnectedImagesCarousel.js
  src/components/ImagesCarousel.js
  src/components/screens/Service.js
  src/components/screens/ServiceTiles.js
  src/helpers/graphqlHelper.js
  src/hooks/staticContent.ts
  src/index.js
  src/navigation/DrawerNavigator.tsx
  src/queries/publicHtmlFiles.js
  src/queries/publicJsonFiles.js
  src/screens/HtmlScreen.js
  src/screens/WasteCollectionScreen.js
Labels: enhancement

#446 fix: public json contents
  src/hooks/staticContent.ts
  src/index.js
  src/queries/BB-BUS/getTop10Ids.js
  src/screens/BB-BUS/IndexScreen.js
Labels: bug, enhancement

#440 Feature: data provider filter in settings
  src/PermanentFilterProvider.tsx
  src/components/BackToTop.js
  src/components/DataListSection.tsx
  src/components/DropdownHeader.js
  src/components/HomeSection.tsx
  src/components/NewsSectionPlaceholder.tsx
  src/components/index.js
  src/components/settings/PermanentFilterSettings.tsx
  src/components/settings/index.js
  src/config/Icon.tsx
  src/config/texts.js
  src/hooks/index.js
  src/hooks/permanentFilter.ts
  src/icons/emptySection.js
  src/icons/index.js
  src/index.js
  src/queries/index.js
  src/queries/newsItems.js
  src/queries/newsItemsDataProvider.js
  src/queries/types.js
  src/reducers/index.ts
  src/reducers/permanentFilterReducer.ts
  src/screens/HomeScreen.js
  src/screens/IndexScreen.js
  src/screens/SettingsScreen.js
  src/types/PermanentFilter.ts
  src/types/index.ts
Labels: enhancement

#448 Update base components
  src/components/Button.js
  src/components/Text.js
Labels: enhancement, refactoring

#447 feature(feedback): Added feedback to detail screens
  src/components/FeedbackFooter.tsx
  src/components/Text.js
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/hooks/appInfo.ts
  src/screens/DetailScreen.js
  src/screens/FeedbackScreen.js
  src/screens/index.js
  src/types/Navigation.ts
Labels: enhancement

#449 feat(pois): filter by location
  src/queries/pointsOfInterest.js
Labels: enhancement

#452 fix: respect `item.bottomDivider` in list hooks if present
  src/hooks/listHooks.js
Labels: enhancement

#455 feat(feedback): Added feedback to bbbus detail and waste screens
  src/components/wasteCalendar/WasteReminderSettings.tsx
  src/screens/BB-BUS/DetailScreen.js
  src/screens/WasteCollectionScreen.js
Labels: enhancement

#450 fix(app-intro): fix app intro content below status bar
  src/screens/AppIntroScreen.tsx
Labels: bug, enhancement

#456 fix(theming): Set the text color for the date picker of waste reminder
  src/components/wasteCalendar/WasteReminderSettings.tsx
Labels: bug

#459 fix(feedback footer): require cycle
  src/components/FeedbackFooter.tsx
Labels: bug

#460 fix(categoryIds): add param to attraction queries
  src/queries/pointsOfInterest.js
  src/queries/tours.js
  src/screens/MultiButtonScreen.tsx
Labels: bug, enhancement

#463 refactor(feedback): string to variables for consistency
  src/components/FeedbackFooter.tsx
  src/config/texts.js
Labels: refactoring

#467 feature: nested services
  src/components/screens/ServiceTiles.js
  src/config/navigation/defaultStackConfig.tsx
  src/screens/TilesScreen.js
  src/types/Navigation.ts
Labels: enhancement

#469 fix(static content): check for content emptiness
  src/components/screens/ServiceTiles.js
  src/hooks/staticContent.ts
Labels: bug, enhancement

#472 fix(waste calendar): Fixed the missing time zone
  src/components/wasteCalendar/WasteReminderSettings.tsx
Labels: bug, enhancement
