Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2023-10, with the labels that each got.

#939 fix(volunteer): the problem of not creating events
  src/components/volunteer/VolunteerFormCalendar.tsx
Labels: bug

#938 feat(disturber): hide the close button on the main server
  src/components/Disturber.tsx
Labels: enhancement

#901 chore(expo): update expo version to 49
  __tests__/components/Button.test.js
  __tests__/components/__snapshots__/Icon.test.js.snap
  app.json
  jest-setup.js
  package.json
  src/components/SettingsToggle.js
  src/components/defectReport/DefectReportCreateForm.tsx
  src/components/noticeboard/NoticeboardCreateForm.tsx
  src/components/noticeboard/NoticeboardMessageForm.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/components/volunteer/VolunteerFormConversation.tsx
  src/components/volunteer/VolunteerFormGroup.tsx
  src/components/volunteer/VolunteerFormProfile.tsx
  src/icons/editSetting.js
  src/icons/lunch.js
  src/navigation/DrawerNavigator.tsx
  src/navigation/MainTabNavigator.tsx
  src/navigation/screenOptions.tsx
  src/screens/FeedbackScreen.js
  yarn.lock
Labels: enhancement, dependencies, refactoring

#917 refactor: additional changes for react navigation 6.x
  src/navigation/AppStackNavigator.tsx
  src/navigation/DrawerNavigator.tsx
Labels: refactoring

#943 refactor: set map preview and list view for augmented reality
  src/components/augmentedReality/ARObjectListItem.js
  src/components/augmentedReality/IconForDownloadType.js
  src/components/augmentedReality/WhatIsARButton.js
  src/screens/MapViewScreen.js
Labels: refactoring

#945 fix: the bug of not navigating back from map view
  src/components/screens/Overviews.js
Labels: bug

#944 fix: the problem that notifications cannot be activated
  app.json
  src/pushNotifications/PermissionHandling.ts
Labels: bug

#948 fix: new data not loading into the list
  src/components/Calendar.tsx
  src/components/EventList.js
  src/components/VerticalList.js
  src/components/screens/EventRecords.js
  src/components/screens/Overviews.js
Labels: bug

#947 fix(navigation): configs without `useContext` and refactorings
  src/SettingsProvider.js
  src/components/IndexMapSwitch.js
  src/components/ListSettingsItem.js
  src/components/map/LocationOverview.tsx
  src/components/settings/LocationSettings.js
  src/config/navigation/config.ts
  src/index.js
  src/navigation/Navigator.tsx
  src/screens/MapViewScreen.js
Labels: bug

#951 fix: navigation type error for volunteer
  src/components/volunteer/VolunteerEventRecord.tsx
  src/components/volunteer/VolunteerGroup.tsx
  src/components/volunteer/VolunteerUser.tsx
  src/hooks/volunteer/header.tsx
Labels: bug

#952 fix: issue with selectors causing the application to crash
  src/components/defectReport/DefectReportCreateForm.tsx
  src/components/screens/consul/Proposals/NewProposal.js
  src/components/volunteer/VolunteerFormCalendar.tsx
Labels: bug

#953 fix: event list screen app crashes on android devices
  src/components/EventList.js
Labels: bug

#949 feat: add a link to the share feature for news
  src/helpers/shareHelper.js
Labels: enhancement

#954 fix: errors in the event list
  src/components/Calendar.tsx
  src/components/EventList.js
  src/components/screens/EventRecords.js
  src/queries/eventRecords.js
  src/queries/index.js
  src/queries/types.ts
Labels: bug

#956 feature: change event list
  package.json
  src/components/EventList.js
  src/hooks/listHooks.js
  yarn.lock
Labels: enhancement

#958 feat: add list to home screen
  src/SettingsProvider.js
  src/components/CardListItem.js
  src/components/ListComponent.js
  src/index.js
  src/queries/types.ts
  src/screens/HomeScreen.js
Labels: enhancement, sue
