Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2023-08, with the labels that each got.

#875 fix: android crash
  eas.json
Labels: bug

#872 chore: update the necessary packages for expo
  package.json
  yarn.lock
Labels: dependencies

#857 feat: integrate custom links for android
  app.json
  config-plugins/withAndroidMailQueriesAndWhatsappPackage.js
Labels: enhancement, codeball:approved

#877 fix: consul input's nesting problem
  src/components/screens/consul/Debates/NewDebate.js
Labels: bug, consul

#874 refactor: adjust polish texts
  src/config/texts.js
Labels: refactoring

#883 fix: optimise augmented reality
  src/components/augmentedReality/AugmentedRealityView.js
  src/config/consts.js
  src/config/device.js
Labels: bug, ar

#884 feat: adjust zoom value of maps
  src/components/defectReport/DefectReportLocationForm.tsx
  src/components/map/LocationOverview.tsx
  src/components/map/Map.tsx
  src/components/settings/LocationSettings.js
Labels: enhancement

#891 feat(opening times): respect `useYear` instead of 1970-hack
  __tests__/helpers/openingHoursHelper.test.ts
  src/components/screens/OpeningTimesCard.js
  src/helpers/openingHoursHelper.ts
  src/queries/pointsOfInterest.js
  src/types/OpeningHour.ts
Labels: enhancement

#890 fix: application crashing on the proposal creation screen for consul
  src/components/consul/selectors/ImageSelector.js
  src/components/form/Input.tsx
  src/components/screens/consul/Debates/NewDebate.js
  src/components/screens/consul/Proposals/NewProposal.js
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/config/consts.js
  src/helpers/consul/dataErrorMessageGenerator.js
  src/hooks/imagePicker.ts
  src/screens/FeedbackScreen.js
Labels: bug, consul

#894 feat: add query variables that can be set from the server for the event
  src/components/widgets/EventWidget.tsx
  src/screens/HomeScreen.js
  src/types/WidgetProps.ts
Labels: enhancement

#897 feat: add setting to show or hide filter by opening times
  src/screens/IndexScreen.js
Labels: enhancement

#904 fix: prevent the open only switcher from being duplicated
  src/screens/IndexScreen.js
Labels: bug

#902 feat: list subcategories on index screen
  src/components/CategoryList.js
Labels: enhancement
