Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2023-01, with the labels that each got.

#724 feat(accessibility): add alternative text to weather icons
  src/components/weather/DailyWeather.tsx
  src/components/weather/HourlyWeather.tsx
  src/components/widgets/WeatherWidget.tsx
  src/screens/WeatherScreen.js
Labels: enhancement, accessibility

#723 refactor(accessibility): change bookmark alternative text
  src/components/FavoritesHeader.tsx
  src/config/consts.js
Labels: enhancement, accessibility

#715 Update publiccode.yml
  publiccode.yml
Labels: codeball:approved

#721 feat(ar): add `ViroSpotLight` and `ViroQuad` to scene
  src/components/augmentedReality/AugmentedRealityView.js
  src/helpers/augmentedReality/downloadObject.js
  src/helpers/augmentedReality/objectParser.js
Labels: enhancement, ar, codeball:needs-careful-review

#725 refactor(accessibility): convert weather forecast to one text
  src/components/weather/DailyWeather.tsx
  src/screens/WeatherScreen.js
Labels: enhancement, accessibility

#729 feat(events): calendar toggle and calendar view
  src/components/Calendar.tsx
  src/components/CalendarListToggle.tsx
  src/components/DataListSection.tsx
  src/components/EventList.js
  src/components/ListComponent.js
  src/components/index.js
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/components/volunteer/VolunteerHomeSection.tsx
  src/components/volunteer/index.ts
  src/components/widgets/EventWidget.tsx
  src/config/Icon.tsx
  src/config/texts.js
  src/helpers/parser/listItemParser.js
  src/icons/calendarToggle.js
  src/icons/index.js
  src/queries/volunteer/calendar.ts
  src/screens/HomeScreen.js
  src/screens/IndexScreen.js
  src/screens/Noticeboard/NoticeboardIndexScreen.tsx
  src/screens/consul/ConsulIndexScreen.js
  src/screens/volunteer/VolunteerIndexScreen.tsx
  src/types/volunteer/calendar.ts
Labels: enhancement, refactoring, codeball:needs-careful-review

#735 fix: delete `groupPrice` because the android app crashed
  src/components/screens/PriceCard.js
Labels: bug, codeball:approved
