Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2023-12, with the labels that each got.

#974 fix: add control to prevent the app from crashing
  src/components/CardListItem.js
Labels: bug

#976 chore: protect the list from changing when refreshing
  src/screens/SUE/SueListScreen.tsx
Labels: enhancement, sue

#977 feat(sue): map marker depending on status
  src/components/map/Map.tsx
  src/screens/SUE/SueMapScreen.tsx
  src/types/Map.ts
Labels: enhancement, sue

#979 feat(sue): reverse geocoding
  src/components/SUE/report/SueReportLocation.tsx
  src/config/texts.js
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#978 feat(sue): improve report form
  src/components/SUE/report/SueReportDescription.tsx
  src/components/SUE/report/SueReportLocation.tsx
  src/components/SUE/report/SueReportUser.tsx
  src/components/consul/selectors/ImageSelector.js
  src/config/consts.js
  src/config/texts.js
  src/helpers/consul/dataErrorMessageGenerator.js
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#955 feat(settings): MoWaS regional keys handling
  src/components/augmentedReality/AugmentedReality.js
  src/components/settings/ListSettings.js
  src/components/settings/MowasRegionSettings.tsx
  src/components/settings/PermanentFilterSettings.tsx
  src/components/settings/index.js
  src/config/texts.js
  src/pushNotifications/TokenHandling.ts
  src/reducers/index.ts
  src/reducers/mowasRegionalKeysReducer.ts
  src/screens/SettingsScreen.js
Labels: enhancement

#972 feat(disturber): add multiple images to disturber
  src/components/Disturber.tsx
  src/components/ImagesCarousel.js
Labels: enhancement

#950 refactor(settings): settings with sub screens instead of tabs
  src/components/augmentedReality/AugmentedReality.js
  src/components/settings/ListSettings.js
  src/components/settings/LocationSettings.js
  src/components/settings/MowasRegionSettings.tsx
  src/components/settings/PermanentFilterSettings.tsx
  src/components/settings/index.js
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/pushNotifications/TokenHandling.ts
  src/reducers/index.ts
  src/reducers/mowasRegionalKeysReducer.ts
  src/screens/SettingsScreen.js
Labels: refactoring

#968 feat: adjustments for map and card list
  src/components/CardListItem.js
  src/components/map/LocationOverview.tsx
  src/components/map/Map.tsx
Labels: enhancement, refactoring

#920 feat: add a text list option with a large image as the first item
  src/components/Text.js
  src/components/TextListItem.tsx
  src/config/consts.js
  src/config/texts.js
  src/hooks/listHooks.js
Labels: enhancement

#980 feat: add `EventSectionHeader` for text list with big picture
  src/components/TextListItem.tsx
  src/hooks/listHooks.js
Labels: bug, enhancement

#981 fix: the errors of the lists
  src/components/CardListItem.js
  src/components/Image.js
  src/components/TextListItem.tsx
  src/hooks/listHooks.js
Labels: bug

#982 feat: update categories when report screen opens
  src/components/SUE/report/SueReportServices.tsx
Labels: enhancement, sue

#983 feat: add link to checkbox on report screen
  src/components/SUE/report/SueReportUser.tsx
  src/config/texts.js
Labels: enhancement, sue

#984 feat: store data on the report screen
  src/components/DeleteHeader.tsx
  src/components/HeaderRight.tsx
  src/components/index.js
  src/config/texts.js
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue
