Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2023-07, with the labels that each got.

#861 fix: a space error between two inputs
  src/screens/WasteCollectionScreen.js
Labels: bug

#864 refactor: change the alert text of the defect reporter
  src/config/texts.js
Labels: refactoring

#865 feat: show alert after the survey is answered
  src/config/texts.js
  src/hooks/surveyHooks.ts
Labels: enhancement

#866 chore: add expo-clipboard package
  package.json
  yarn.lock
Labels: dependencies

#860 feat(opening times): dates with parsed TMB year
  __tests__/helpers/openingHoursHelper.test.ts
  jest-setup.js
  src/components/screens/OpeningTimesCard.js
  src/helpers/openingHoursHelper.ts
Labels: enhancement
