Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2023-09, with the labels that each got.

#905 feat: add a multi-button feature for navigating screens in the app
  src/components/MultiButtonWithSubQuery.tsx
Labels: enhancement

#908 feat: add html section above the survey list
  src/components/widgets/SurveyWidget.tsx
  src/screens/SurveyOverviewScreen.tsx
  src/types/WidgetProps.ts
Labels: enhancement

#919 refactor: remove the date from the list and sort the list alphabetically
  src/helpers/parser/listItemParser.js
Labels: refactoring

#895 refactor: ability to switch navigation through server config
  src/SettingsProvider.js
  src/config/navigation/config.ts
Labels: refactoring

#918 refactor: adjust max screen with to fit all phone sizes
  src/config/consts.js
Labels: refactoring

#892 refactor: reduce auth refreshs
  App.js
  src/screens/DetailScreen.js
  src/screens/HomeScreen.js
  src/screens/HtmlScreen.js
  src/screens/IndexScreen.js
Labels: refactoring

#916 feat: add link to share feature
  src/components/infoCard/InfoCard.tsx
  src/helpers/linkHelper.js
  src/helpers/shareHelper.js
Labels: enhancement

#915 feat: add dynamic intro content for points of interest list
  src/screens/IndexScreen.js
Labels: enhancement

#906 refactor: change navigation structure
  src/config/navigation/defaultStackConfig.tsx
  src/config/navigation/tabConfig.tsx
  src/config/texts.js
  src/types/Navigation.ts
Labels: enhancement, refactoring

#903 feat: add ability for a factor to size tiles
  src/components/screens/Service.tsx
  src/components/screens/ServiceTile.tsx
Labels: enhancement

#900 refactor: add own color for refresh control
  src/components/Calendar.tsx
  src/components/CategoryList.js
  src/components/ConnectedImagesCarousel.js
  src/components/CrossData.tsx
  src/components/DataListSection.tsx
  src/components/Image.js
  src/components/ImagesCarousel.js
  src/components/LoadingSpinner.tsx
  src/components/MediaSection.js
  src/components/SettingsToggle.js
  src/components/VerticalList.js
  src/components/augmentedReality/IconForDownloadType.js
  src/components/map/LocationOverview.tsx
  src/components/screens/About.js
  src/components/screens/EventRecord.js
  src/components/screens/ServiceTiles.js
  src/components/wasteCalendar/WasteReminderSettings.tsx
  src/config/colors.js
  src/hooks/pullToRefetch.tsx
  src/index.js
  src/screens/BB-BUS/DetailScreen.js
  src/screens/BB-BUS/IndexScreen.js
  src/screens/BookmarkCategoryScreen.js
  src/screens/ConstructionSiteDetailScreen.js
  src/screens/ConstructionSiteOverviewScreen.js
  src/screens/DefectReport/DefectReportFormScreen.tsx
  src/screens/DetailScreen.js
  src/screens/HomeScreen.js
  src/screens/HtmlScreen.js
  src/screens/IndexScreen.js
  src/screens/LunchScreen.js
  src/screens/NestedInfoScreen.tsx
  src/screens/Noticeboard/NoticeboardFormScreen.tsx
  src/screens/Noticeboard/NoticeboardIndexScreen.tsx
  src/screens/OParl/OParlDetailScreen.tsx
  src/screens/SettingsScreen.js
  src/screens/WasteCollectionScreen.js
  src/screens/WeatherScreen.js
  src/screens/WebScreen.js
  src/screens/volunteer/VolunteerDetailScreen.tsx
  src/screens/volunteer/VolunteerHomeScreen.tsx
  src/screens/volunteer/VolunteerIndexScreen.tsx
  src/screens/volunteer/VolunteerPersonalScreen.tsx
Labels: refactoring

#899 refactor: unify structures
  src/components/EmptyMessage.js
  src/components/ImagesCarouselItem.js
  src/components/IndexFilterElement.js
  src/components/Wrapper.js
  src/components/consul/detail/ConsulCommentList.js
  src/components/consul/detail/ConsulVideo.js
  src/components/consul/selectors/DocumentSelector.js
  src/components/consul/selectors/ImageSelector.js
  src/components/screens/consul/Debates/NewDebate.js
  src/components/screens/consul/Proposals/NewProposal.js
  src/navigation/DrawerNavigatorItem.js
  src/navigation/DrawerNavigatorItems.js
  src/screens/TilesScreen.js
  src/screens/WasteCollectionScreen.js
Labels: refactoring

#896 refactor: use `SectionHeader` everywhere
  src/components/CategoryList.js
  src/components/HomeService.js
  src/components/Offer.js
  src/components/SectionHeader.tsx
  src/components/augmentedReality/ARObjectList.js
  src/components/augmentedReality/AugmentedReality.js
  src/components/consul/detail/ConsulCommentList.js
  src/components/consul/detail/ConsulDocumentList.js
  src/components/consul/detail/ConsulSupporting.js
  src/components/consul/detail/ConsulTagList.js
  src/components/consul/detail/ConsulVoting.js
  src/components/consul/list/ConsulList.js
  src/components/screens/EventRecord.js
  src/components/screens/NewsItem.js
  src/components/screens/OperatingCompany.tsx
  src/components/screens/PointOfInterest.js
  src/components/screens/ServiceTiles.js
  src/components/screens/Tour.js
  src/components/screens/TourCard.js
  src/components/screens/consul/Debates/DebateDetail.js
  src/components/screens/consul/Polls/PollDetail.js
  src/components/screens/consul/Proposals/ProposalDetail.js
  src/components/screens/consul/UserComments/UserCommentDetail.js
  src/components/volunteer/VolunteerEventRecord.tsx
  src/components/volunteer/VolunteerGroup.tsx
  src/components/volunteer/VolunteerUser.tsx
  src/screens/ConstructionSiteDetailScreen.js
  src/screens/Noticeboard/NoticeboardFormScreen.tsx
  src/screens/WeatherScreen.js
  src/screens/consul/LoginRegister/ConsulLoginScreen.js
  src/screens/consul/LoginRegister/ConsulRegisterScreen.js
  src/screens/volunteer/VolunteerLoginScreen.tsx
  src/screens/volunteer/VolunteerRegistrationScreen.tsx
  src/screens/volunteer/VolunteerSignupScreen.tsx
Labels: refactoring

#922 feat(web urls): merge system dependent
  src/helpers/linkHelper.js
Labels: enhancement

#914 feat: add secret icons screen to servicetiles
  src/config/Icon.tsx
  src/config/navigation/defaultStackConfig.tsx
  src/screens/doc/DocIconsScreen.tsx
  src/screens/doc/index.ts
  src/screens/index.js
  src/types/Navigation.ts
Labels: enhancement, refactoring

#912 feature: add different sizes and properties for button
  src/components/Button.js
Labels: enhancement

#909 feat: new module disturber
  src/components/ConnectedImagesCarousel.js
  src/components/Disturber.tsx
  src/components/HomeService.js
  src/components/index.js
  src/helpers/momentHelper.js
  src/screens/HomeScreen.js
  src/screens/LunchScreen.js
Labels: enhancement

#921 feat: full screen map in location overview
  src/components/HeaderLeft.tsx
  src/components/IndexMapSwitch.js
  src/components/VerticalList.js
  src/components/Wrapper.js
  src/components/index.js
  src/components/map/LocationOverview.tsx
  src/components/map/Map.tsx
  src/helpers/parser/listItemParser.js
  src/queries/pointsOfInterest.js
  src/screens/IndexScreen.js
  src/screens/consul/ConsulIndexScreen.js
  src/types/Map.ts
Labels: enhancement

#924 feature: show available vehicles in detail screen
  src/components/screens/AvailableVehicles.tsx
  src/components/screens/PointOfInterest.js
  src/components/screens/index.js
  src/config/texts.js
  src/queries/pointsOfInterest.js
Labels: enhancement

#925 fix: add undefined control to url
  src/helpers/linkHelper.js
Labels: bug

#923 feature: list departure times in detail screen
  src/components/screens/AvailableVehicles.tsx
  src/components/screens/PointOfInterest.js
  src/components/screens/TimeTables.tsx
  src/components/screens/index.js
  src/config/texts.js
  src/queries/pointsOfInterest.js
  src/screens/DetailScreen.js
Labels: enhancement

#930 feat: update the header according to the initial filter
  src/screens/IndexScreen.js
Labels: enhancement

#929 refactor: remove hide button in preview
  src/components/map/LocationOverview.tsx
  src/components/map/Map.tsx
Labels: refactoring

#937 fix: not showing a description when adding a link to the organiser
  src/queries/eventRecords.js
Labels: bug

#928 feat:(map icons): render two icons in some cases
  src/components/map/Map.tsx
Labels: enhancement

#927 fix: solve detail screen rerender problem
  src/components/screens/TimeTables.tsx
  src/screens/DetailScreen.js
Labels: bug
