Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2023-03, with the labels that each got.

#758 fix: push notification settings
  src/pushNotifications/PermissionHandling.ts
  src/pushNotifications/TokenHandling.ts
Labels: bug

#737 feat(accessibility): add new labels for input buttons
  src/components/BB-BUS/TextSearch.js
  src/components/form/InputSecureTextIcon.tsx
  src/config/texts.js
Labels: enhancement, accessibility, codeball:needs-careful-review

#759 feat(waste calendar): add possibility for two step ui
  src/config/texts.js
  src/screens/WasteCollectionScreen.js
Labels: enhancement, codeball:approved

#756 chore: update react native render html package
  package.json
  src/components/HtmlView.js
  src/config/consts.js
  src/config/styles/html.js
  yarn.lock
Labels: dependencies, codeball:needs-careful-review

#770 fix: fix param errors when navigating between the same pages
  src/navigation/DrawerNavigatorItem.js
Labels: bug, codeball:approved

#727 chore: update react native elements
  package.json
  src/components/BB-BUS/Block.js
  src/components/CategoryListItem.js
  src/components/Checkbox.js
  src/components/Image.js
  src/components/ListSettingsItem.js
  src/components/Modal.js
  src/components/OptionToggle.tsx
  src/components/SettingsToggle.js
  src/components/TextListItem.tsx
  src/components/augmentedReality/ARObjectListItem.js
  src/components/consul/list/ConsulListItem.js
  src/components/form/Input.tsx
  src/components/oParl/previews/OParlPreviewEntry.tsx
  src/components/volunteer/VolunteerApplicantListItem.tsx
  src/components/volunteer/VolunteerConversationListItem.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/components/volunteer/VolunteerFormGroup.tsx
  src/components/volunteer/VolunteerPostListItem.tsx
  src/components/wasteCalendar/WasteReminderSettings.tsx
  src/screens/EncounterRegistrationScreen.tsx
  yarn.lock
Labels: dependencies, codeball:needs-careful-review

#769 feat(iframe): add iframe plugin
  package.json
  src/components/HtmlView.js
  yarn.lock
Labels: enhancement

#739 feat(accessibility): add provider and listeners
  src/AccessibilityProvider.tsx
  src/helpers/accessibilityListeners.ts
  src/helpers/index.js
  src/index.js
  src/types/Accessibility.ts
  src/types/index.ts
Labels: enhancement, accessibility

#778 feat(accessibility): add bold option to all text styles
  src/components/HtmlView.js
  src/components/StorySection.js
  src/components/Text.js
  src/config/styles/html.js
  src/config/styles/index.js
Labels: accessibility

#788 fix: solve json parse error
  src/queries/mediaContent.js
  src/queries/waterTemperature.js
Labels: bug, codeball:approved

#786 fix(VirtualisedLists): replace `ScrollView` with `FlatList`
  src/screens/HomeScreen.js
Labels: bug, codeball:needs-careful-review

#784 chore(expo sdk): upgrade to 47
  .nvmrc
  eas.json
  package.json
  yarn.lock
Labels: enhancement, dependencies, codeball:needs-careful-review

#790 feat(waste calendar): preselect if there is only one street
  src/screens/WasteCollectionScreen.js
Labels: enhancement

#799 feat: change the opacity of the options in finished surveys
  src/components/survey/SurveyAnswer.tsx
Labels: enhancement

#795 fix: click problem for inactive survey
  src/components/Radiobutton.js
  src/components/survey/SurveyAnswer.tsx
Labels: bug

#808 refactor: set opacity for finished surveys options
  src/components/survey/SurveyAnswer.tsx
  src/screens/SurveyDetailScreen.tsx
Labels: refactoring

#767 feat: delete the white bar on the edges
  __tests__/components/Wrapper.test.js
  __tests__/components/__snapshots__/Wrapper.test.js.snap
  src/components/BB-BUS/TextBlock.js
  src/components/CardListItem.js
  src/components/Checkbox.js
  src/components/OrientationAwareIcon.tsx
  src/components/Wrapper.js
  src/components/map/Map.tsx
Labels: enhancement, codeball:needs-careful-review

#805 feat: add an intro text above the event list
  src/screens/IndexScreen.js
Labels: enhancement, codeball:approved
