Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2024-07, with the labels that each got.

#1156 feat: update total image size format
  src/components/augmentedReality/ARObjectList.js
  src/helpers/augmentedReality/progressSizeGenerator.js
  src/helpers/fileSizeHelper.ts
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#1152 feat(sue): improve the ability to get coordinate information from a photo
  src/components/SUE/report/SueReportDescription.tsx
  src/components/consul/selectors/ImageSelector.js
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#1153 feat(sue): bug fixes and improvements
  src/components/SUE/report/SueReportDescription.tsx
  src/components/SUE/report/SueReportLocation.tsx
  src/components/SUE/report/SueReportUser.tsx
  src/components/consul/selectors/ImageSelector.js
  src/config/texts.js
  src/hooks/reverseGeocode.ts
  src/screens/SUE/SueListScreen.tsx
  src/screens/SUE/SueMapViewScreen.tsx
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#1158 feat(sue): improve performance problems
  src/ConfigurationsProvider.tsx
  src/components/ImagesCarousel.js
  src/components/SUE/report/SueReportDescription.tsx
  src/components/SUE/report/SueReportServices.tsx
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#1157 chore(expo): update expo version to 51.0.17
  package.json
  src/ConfigurationsProvider.tsx
  src/components/ImagesCarousel.js
  src/components/SUE/report/SueReportDescription.tsx
  src/components/SUE/report/SueReportServices.tsx
  src/screens/SUE/SueReportScreen.tsx
  yarn.lock
Labels: enhancement

#1161 fix(sue): remove throwing errors where not needed
  src/components/SUE/report/SueReportLocation.tsx
  src/screens/SUE/SueMapViewScreen.tsx
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#1165 feat: add control to open times on detail screen
  src/components/infoCard/InfoCard.tsx
  src/components/screens/PointOfInterest.js
Labels: enhancement

#1155 feat(sue): update alerts according to location permissions
  package.json
  src/ConfigurationsProvider.tsx
  src/components/CardListItem.js
  src/components/ImageMessage.js
  src/components/ImagesCarousel.js
  src/components/SUE/report/SueReportDescription.tsx
  src/components/SUE/report/SueReportLocation.tsx
  src/components/SUE/report/SueReportSend.tsx
  src/components/SUE/report/SueReportServices.tsx
  src/components/SUE/report/SueReportUser.tsx
  src/components/settings/LocationSettings.js
  src/config/sue/default.ts
  src/config/texts.js
  src/hooks/openWebScreen.ts
  src/screens/SUE/SueMapScreen.tsx
  src/screens/SUE/SueMapViewScreen.tsx
  src/screens/SUE/SueReportScreen.tsx
  src/screens/SettingsScreen.js
  yarn.lock
Labels: enhancement, sue

#1164 feat(sue): adjust according to api update
  src/config/sue/default.ts
  src/helpers/sueHelper.ts
  src/queries/SUE/requests.tsx
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#1167 feat: add filter for opening times on detail screen
  src/components/screens/PointOfInterest.js
Labels: enhancement

#1168 chore(expo): update expo version to 51.0.22
  package.json
  yarn.lock
Labels: dependencies

#1169 fix: http pages not opening on ios platform
  app.json
Labels: bug

#1170 refactor: update the font loading as in the document
  App.js
Labels: refactoring

#1173 fix(config): app not loading problem
  src/ConfigurationsProvider.tsx
Labels: bug

#1163 feat(events): show all appointments of recurring events
  package.json
  src/ReactQueryClient.tsx
  src/SettingsProvider.js
  src/components/Calendar.tsx
  src/components/CrossData.tsx
  src/components/EventList.js
  src/components/calendarArrows.tsx
  src/components/screens/EventRecord.js
  src/components/screens/EventRecords.js
  src/components/screens/OpeningTimesCard.js
  src/components/screens/Overviews.js
  src/components/widgets/EventWidget.tsx
  src/helpers/parser/listItemParser.js
  src/queries/eventRecords.js
  src/queries/index.js
  src/queries/types.ts
  src/screens/SUE/SueListScreen.tsx
  src/screens/Voucher/VoucherDetailScreen.tsx
  src/screens/Voucher/VoucherIndexScreen.tsx
  yarn.lock
Labels: enhancement
