Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2024-12, with the labels that each got.

#1215 feat: add link that opens from browser
  app.json
  src/components/MultiButtonWithSubQuery.tsx
  src/screens/WebScreen.js
  src/types/SubQuery.ts
Labels: enhancement

#1217 feat: add event suggestion screen
  src/components/EventList.js
  src/components/EventSuggeestionButton.tsx
  src/components/index.js
  src/components/screens/EventRecords.js
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/screens/EventSuggestionScreen.tsx
  src/screens/index.js
  src/types/Navigation.ts
Labels: enhancement

#1221 feat(sue): update config when report screen opens
  src/ConfigurationsProvider.tsx
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement, sue

#1223 fix(overviews): improve location-based sorting logic and clean up redundant code
  src/components/screens/Overviews.js
Labels: bug

#1218 fix: keyboard issues
  app.json
  src/components/Chat.js
  src/components/DefaultKeyboardAvoidingView.tsx
  src/navigation/MainTabNavigator.tsx
Labels: bug

#1219 fix: start/end date selection problem
  src/components/filter/Filter.tsx
Labels: bug, filter

#1224 fix(bookmarks): multi events handling
  src/components/DataListSection.tsx
  src/components/bookmarks/BookmarkSection.tsx
  src/queries/eventRecords.js
  src/screens/BookmarkCategoryScreen.js
Labels: bug

#1220 feat(sue): add clustering for report map view
  src/components/SUE/report/SueReportLocation.tsx
  src/screens/SUE/SueMapViewScreen.tsx
Labels: enhancement, sue

#1225 feat: enhance location-based sorting functionality
  src/components/screens/Overviews.js
Labels: enhancement
