Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2024-08, with the labels that each got.

#1177 feat(noticeboard): add the ability to add noticeboards in different categories
  src/components/noticeboard/NoticeboardCreateForm.tsx
  src/config/texts.js
  src/screens/Noticeboard/NoticeboardFormScreen.tsx
  src/screens/Noticeboard/NoticeboardIndexScreen.tsx
Labels: enhancement

#1178 feat(widget): add static content widget
  src/components/widgets/CustomWidget.tsx
  src/components/widgets/Widgets.tsx
  src/config/texts.js
  src/types/WidgetProps.ts
Labels: enhancement

#1179 feat: integrate adaptive icon
  app.json
  assets/adaptive-icon.png
Labels: enhancement

#1181 refactor: update README example screens
  example-screens.png
Labels: enhancement, refactoring

#1176 fix(sue): report not sending error
  src/components/consul/selectors/ImageSelector.js
  src/queries/SUE/requests.tsx
Labels: bug

#1174 fix(sue): required input problem in config
  src/components/consul/selectors/ImageSelector.js
  src/config/sue/default.ts
  src/queries/SUE/configurations.tsx
  src/queries/SUE/requests.tsx
  src/screens/SUE/SueReportScreen.tsx
Labels: bug, sue

#1183 feat(tabler): integration of tabler icon
  assets/tabler-icons/2.47.0/glyph-map.json
  assets/tabler-icons/2.47.0/tabler-icons.ttf
  src/config/fonts.ts
  src/config/icons/Icon.tsx
  src/config/icons/Tabler.tsx
  src/config/icons/index.ts
  src/config/index.js
  src/config/navigation/tabConfig.tsx
Labels: enhancement
