Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2024-10, with the labels that each got.

#1194 fix(sue): location inaccuracy from address
  src/components/SUE/report/SueReportLocation.tsx
Labels: bug, sue

#1189 fix: default prop error
  src/components/BB-BUS/IndexFilter.js
  src/components/BB-BUS/ServiceList.js
  src/components/Button.js
  src/components/CardListItem.js
  src/components/CategoryList.js
  src/components/CategoryListItem.js
  src/components/Checkbox.js
  src/components/ConnectedImagesCarousel.js
  src/components/DiagonalGradient.js
  src/components/EmptyMessage.js
  src/components/HtmlView.js
  src/components/Image.js
  src/components/Logo.js
  src/components/Modal.js
  src/components/Radiobutton.js
  src/components/TextListItem.tsx
  src/components/VerticalList.js
  src/components/form/PickerInput.js
  src/navigation/DrawerNavigatorItems.js
Labels: bug

#1190 fix: key error & key extractor error
  src/components/CardListItem.js
  src/components/wasteCalendar/WasteReminderSettings.tsx
  src/screens/AppIntroScreen.tsx
Labels: bug

#1192 fix: delete warnings in the code
  src/hooks/staticContent.ts
Labels: bug

#1193 feat(noticeboard): add pdf upload and download feature
  app.json
  package.json
  src/components/DocumentList.tsx
  src/components/DocumentListItem.tsx
  src/components/consul/selectors/DocumentSelector.js
  src/components/index.js
  src/components/noticeboard/NoticeboardCreateForm.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/config/consts.js
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/helpers/consul/dataErrorMessageGenerator.js
  src/helpers/documentDownloadHelper.ts
  src/helpers/index.js
  src/queries/mediaContent.js
  src/screens/Noticeboard/NoticeboardFormScreen.tsx
  src/screens/PdfScreen.tsx
  src/screens/WebScreen.js
  src/screens/index.js
  src/types/Navigation.ts
  yarn.lock
Labels: enhancement

#1187 feat(filter): create provider for filter
  src/ConfigurationsProvider.tsx
  src/PermanentFilterProvider.tsx
  src/config/appDesignSystem/filter.ts
  src/config/appDesignSystem/index.ts
  src/helpers/storageHelper.js
  src/hooks/permanentFilter.ts
  src/queries/index.js
  src/queries/resourceFilters.ts
  src/queries/types.ts
  src/reducers/filterReducer.ts
  src/reducers/index.ts
  src/reducers/permanentFilterReducer.ts
  src/types/PermanentFilter.ts
  src/types/index.ts
Labels: enhancement, filter

#1198 fix: the problem of personalized tiles not being sorted correctly
  src/components/screens/DraggableGrid.tsx
  src/components/screens/Service.tsx
  src/hooks/personalizedTiles.ts
Labels: bug

#1199 feat: add `autoplayInterval` to slider
  src/components/ImagesCarousel.js
Labels: enhancement

#1202 feat: remove key warnings
  src/components/CardListItem.js
  src/components/screens/DraggableGrid.tsx
  src/components/screens/Service.tsx
  src/hooks/listHooks.js
Labels: enhancement

#1203 feat(weather): integrate new weather detail screen
  src/components/Wrapper.js
  src/components/weather/DailyWeather.tsx
  src/components/weather/HourlyWeather.tsx
  src/components/weather/WeatherAlert.tsx
  src/config/Icon.tsx
  src/config/texts.js
  src/icons/index.js
  src/icons/maxTemperature.js
  src/icons/minTemperature.js
  src/icons/rain.js
  src/icons/sunDown.js
  src/icons/sunUp.js
  src/screens/WeatherScreen.js
Labels: enhancement

#1206 fix: home section query with react-query
  src/components/HomeSection.tsx
  src/queries/eventRecords.js
  src/screens/HomeScreen.js
Labels: bug

#1205 feat(event records): reduce queried fields and new query for count
  src/components/widgets/EventWidget.tsx
  src/queries/eventRecords.js
  src/queries/index.js
  src/queries/types.ts
Labels: enhancement

#1204 feat: add the minimum version value for macOS platform
  app.json
Labels: enhancement

#1207 fix: event category query not working
  src/queries/eventRecords.js
Labels: bug

#1208 fix: category naming problem
  src/components/screens/PointOfInterest.js
  src/helpers/parser/listItemParser.js
  src/queries/pointsOfInterest.js
Labels: bug

#1209 fix: reverse geocoding request error
  src/hooks/reverseGeocode.ts
Labels: bug, sue

#1038 feat(whistleblow): integration of globaleaks
  package.json
  src/SettingsProvider.js
  src/components/index.js
  src/components/whistleblow/WhistleblowReportForm.tsx
  src/components/whistleblow/index.ts
  src/config/Icon.tsx
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/helpers/index.js
  src/helpers/whistleblow/globaleaks/index.ts
  src/helpers/whistleblow/globaleaks/proofOfWork.ts
  src/helpers/whistleblow/index.ts
  src/index.js
  src/queries/index.js
  src/queries/whistleblow/auth.ts
  src/queries/whistleblow/index.ts
  src/queries/whistleblow/whistleblower.ts
  src/screens/NestedInfoScreen.tsx
  src/screens/index.js
  src/screens/whistleblow/WhistleblowFormScreen.tsx
  src/screens/whistleblow/index.ts
  src/types/Navigation.ts
  src/types/SubQuery.ts
  src/types/index.ts
  src/types/whistleblow/globaleaks/index.ts
  src/types/whistleblow/globaleaks/submission.ts
  src/types/whistleblow/index.ts
  yarn.lock
Labels: enhancement, whistleblow

#1211 fix: header left problem on subcategory screen
  src/helpers/parser/listItemParser.js
Labels: bug
