Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2025-02, with the labels that each got.

#1240 feat(tab): add customizable service tile screen
  src/config/navigation/defaultStackConfig.tsx
  src/config/navigation/tabConfig.tsx
  src/navigation/MainTabNavigator.tsx
  src/types/Navigation.ts
Labels: enhancement

#1242 fix(sue): unable to overwrite configuration error
  src/ConfigurationsProvider.tsx
Labels: bug, sue

#1233 feat(sue): hide alternate location selection button
  src/components/settings/LocationSettings.js
Labels: enhancement, sue

#1232 feat(sue) increased contrast pin colors
  src/components/SUE/report/SueReportLocation.tsx
  src/components/map/Map.tsx
  src/config/appDesignSystem/default.ts
  src/screens/SUE/SueMapScreen.tsx
  src/types/Map.ts
Labels: enhancement, sue

#1248 fix(sue): input's header design problem
  src/components/SUE/report/SueReportSend.tsx
Labels: bug, sue

#1247 fix(map): the pin problem on the map for android
  patches/react-native-maps+1.18.0.patch
Labels: bug

#1244 feature(sue): add `SueHomeScreen`
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/screens/SUE/SueHomeScreen.tsx
  src/screens/SUE/SueListScreen.tsx
  src/screens/SUE/index.ts
  src/types/Navigation.ts
Labels: enhancement, sue

#1246 feat(waste): add export functionality for waste calendar
  src/components/waste/WasteCollectionSettings.tsx
  src/config/texts.js
  src/screens/WasteCollectionScreen.js
Labels: enhancement

#1245 feat(waste): enhance text localization in waste components
  src/components/waste/WasteCollectionSettings.tsx
  src/components/waste/WasteHeader.tsx
  src/components/waste/WasteInputForm.tsx
  src/config/texts.js
  src/screens/WasteCollectionScreen.js
Labels: enhancement

#1250 fix(waste): the problem of autocomplete list not showing up on android
  src/components/waste/WasteInputForm.tsx
  src/hooks/waste.tsx
Labels: bug

#1249 fix(waste): the unmanageability of notifications
  __maestro__/flows/waste/location.yml
  src/components/waste/WasteCollectionSettings.tsx
  src/components/waste/WasteInputForm.tsx
  src/config/texts.js
  src/hooks/waste.tsx
  src/pushNotifications/PermissionHandling.ts
  src/reducers/wasteSettingsReducer.ts
  src/screens/WasteCollectionScreen.js
Labels: bug

#1243 feat(waste): updates, refactoring and new reducer
  __maestro__/flows/waste/location.yml
  package.json
  src/PermanentFilterProvider.tsx
  src/SettingsProvider.js
  src/components/Calendar.tsx
  src/components/CrossData.tsx
  src/components/FeedbackFooter.tsx
  src/components/GroupedList.tsx
  src/components/GroupedListItem.tsx
  src/components/GroupedSectionHeader.tsx
  src/components/HeaderLeft.tsx
  src/components/ListComponent.js
  src/components/NoTouchDay.tsx
  src/components/Text.js
  src/components/index.js
  src/components/settings/MowasRegionSettings.tsx
  src/components/waste/WasteCalendarLegend.tsx
  src/components/waste/WasteCalendarLegendEntry.tsx
  src/components/waste/WasteCollectionListItem.tsx
  src/components/waste/WasteCollectionSettings.tsx
  src/components/waste/WasteHeader.tsx
  src/components/waste/WasteInputForm.tsx
  src/components/waste/WasteList.tsx
  src/components/waste/index.ts
  src/components/wasteCalendar/ReminderSettingsReducer.ts
  src/components/wasteCalendar/WasteCalendarLegend.tsx
  src/components/wasteCalendar/WasteReminderSettings.tsx
  src/components/wasteCalendar/index.ts
  src/components/widgets/EventWidget.tsx
  src/config/consts.js
  src/config/icons/Icon.tsx
  src/config/texts.js
  src/helpers/htmlViewHelper.js
  src/helpers/parser/listItemParser.js
  src/helpers/updateResourceFiltersStateHelper.ts
  src/hooks/index.js
  src/hooks/listHooks.js
  src/hooks/waste.tsx
  src/icons/index.js
  src/icons/keyboardArrowUpDown.js
  src/index.js
  src/jsonValidation/reminderSettingsValidation.ts
  src/pushNotifications/PermissionHandling.ts
  src/pushNotifications/WasteReminder.ts
  src/reducers/index.ts
  src/reducers/mowasRegionalKeysReducer.ts
  src/reducers/permanentFilterReducer.ts
  src/reducers/resourceFiltersReducer.ts
  src/reducers/wasteSettingsReducer.ts
  src/screens/OParl/OParlCalendarScreen.tsx
  src/screens/WasteCollectionScreen.js
  src/screens/WasteReminderScreen.js
  src/types/Waste.ts
  src/types/index.ts
  yarn.lock
Labels: enhancement, refactoring

#1251 feat: update permissions according to google policies
  app.json
Labels: enhancement

#1253 fix: the back button issue on the `IndexScreen? placed in tab
  src/components/screens/Overviews.js
Labels: bug

#1252 fix(sue): the problem of not showing data in list view
  src/components/filter/Filter.tsx
  src/components/screens/EventRecords.js
  src/components/screens/Overviews.js
  src/screens/ConstructionSiteOverviewScreen.js
  src/screens/Noticeboard/NoticeboardIndexScreen.tsx
  src/screens/SUE/SueListScreen.tsx
Labels: bug

#1254 refactor: update event record query structure
  src/queries/eventRecords.js
Labels: bug

#1255 fix the design bug of the oparl list
  src/components/oParl/previews/MeetingPreview.tsx
  src/components/oParl/previews/OParlItemPreview.tsx
  src/components/oParl/previews/OParlPreviewEntry.tsx
  src/components/oParl/previews/PersonPreview.tsx
  src/components/oParl/sections/OParlPreviewSection.tsx
Labels: bug

#1256 feat: add page title to `initialParams`
  src/config/navigation/defaultStackConfig.tsx
Labels: enhancement

#1257 fix(waste): date time picker not centered
  src/components/waste/WasteCollectionSettings.tsx
Labels: bug

#1258 fix(waste): adjust date time picker layout for Android
  src/components/waste/WasteCollectionSettings.tsx
Labels: bug

#1260 move secrete template file from src/config to root
  secrets.js.erb.tmpl
Labels: refactoring

#1262 refactor(navigation): streamline navigator configuration and imports
  src/config/navigation/config.ts
  src/config/navigation/tabConfig.tsx
  src/navigation/DrawerNavigator.tsx
  src/navigation/MainTabNavigator.tsx
  src/navigation/Navigator.tsx
  src/types/Navigation.ts
Labels: refactoring

#1263 refactor: remove unused static content logic and clean up imports
  src/screens/HomeScreen.js
Labels: enhancement

#1264 fix: remove unused back button in header for android
  src/components/HeaderLeft.tsx
Labels: bug

#1268 refactor: reorganize navigation stack configuration
  src/config/navigation/defaultStackConfig.tsx
  src/helpers/parser/listItemParser.js
Labels: refactoring

#1266 feat: add `isOverlayFilter` prop to `Dropdown` components
  src/components/DropdownSelect.js
  src/components/filter/DateFilter.tsx
  src/components/filter/DropdownFilter.tsx
  src/components/filter/Filter.tsx
  src/components/filter/FilterComponent.tsx
  src/components/widgets/EventWidget.tsx
  src/config/navigation/defaultStackConfig.tsx
  src/helpers/parser/listItemParser.js
  src/hooks/listHooks.js
Labels: bug

#1269 fix: the problem in the slider that starts over when you want to pause
  src/components/ImagesCarousel.js
Labels: bug

#1272 fix: update react-native-gifted-chat to version 2.7.3
  package.json
  src/components/Chat.js
  yarn.lock
Labels: bug

#1274 release: add script for EAS Update
  .github/scripts/eas-update.js
  app.json
  app.json.erb.tmpl
  package.json
  src/components/VersionNumber.js
Labels: enhancement

#1275 feat(web): adjust deceleration rate based on platform
  src/screens/WebScreen.tsx
Labels: bug

#1273 feat(navigation): update react-navigation from 6 to 7
  package.json
  src/config/navigation/tabConfig.tsx
  src/navigation/MainTabNavigator.tsx
  src/navigation/Navigator.tsx
  src/navigation/screenOptions.tsx
  src/types/Navigation.ts
  yarn.lock
Labels: enhancement, dependencies

#1278 fix(survey): add conditional rendering for date components
  src/screens/SurveyDetailScreen.tsx
Labels: bug

#1276 feat(tab): add `tabBarLabelStyle` to tab configuration
  src/config/navigation/tabConfig.tsx
  src/navigation/MainTabNavigator.tsx
  src/types/Navigation.ts
Labels: enhancement

#1277 feat: add route prop to `LocationOverview` component
  src/components/map/LocationOverview.tsx
Labels: enhancement

#1280 fix(survey): enhance header styling in `SurveyOverviewScreen`
  src/screens/SurveyOverviewScreen.tsx
Labels: bug

#1281 fix(navigation): update screen options and navigation method
  src/config/navigation/defaultStackConfig.tsx
  src/navigation/DrawerNavigatorItem.js
  src/screens/WasteCollectionScreen.js
  src/screens/WasteCollectionSettingsScreen.tsx
Labels: bug

#1283 fix: center align `DateTimePicker` component
  src/components/form/DateTimeInput.tsx
Labels: bug

#1282 fix: categories not showing up on noticeboard
  src/helpers/parser/listItemParser.js
Labels: bug
