Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2025-08, with the labels that each got.

#1363 fix(tiles): errors in customizable
  src/components/screens/ServiceTile.tsx
Labels: bug

#1365 fix: the problem of invisibility in non-customizable tiles
  src/hooks/personalizedTiles.ts
Labels: bug

#1354 feat: add `CitySelectionScreen` for city selection functionality
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/helpers/citySelectionHelper.ts
  src/helpers/index.js
  src/screens/CitySelectionScreen.tsx
  src/screens/index.js
  src/types/Navigation.ts
Labels: enhancement

#1356 feat(volunteer): implement group search functionality
  src/components/filter/DateFilter.tsx
  src/components/filter/DropdownFilter.tsx
  src/components/filter/Filter.tsx
  src/components/volunteer/VolunteerGroup.tsx
  src/components/volunteer/VolunteerGroupSearch.tsx
  src/components/volunteer/VolunteerGroupSearchField.tsx
  src/components/volunteer/VolunteerPostListItem.tsx
  src/components/volunteer/VolunteerPosts.tsx
  src/components/volunteer/index.ts
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/hooks/volunteer/data.ts
  src/icons/lupe.js
  src/queries/index.js
  src/queries/types.ts
  src/queries/volunteer/group.ts
  src/screens/volunteer/VolunteerGroupSearchScreen.tsx
  src/screens/volunteer/VolunteerIndexScreen.tsx
  src/screens/volunteer/index.ts
  src/types/Navigation.ts
  src/types/ResourceFilters.ts
Labels: enhancement, volunteer

#1361 feat(volunteer): enhance appointment handling
  src/components/screens/OpeningTimesCard.js
  src/components/volunteer/VolunteerAppointmentsCard.tsx
  src/components/volunteer/VolunteerEventRecord.tsx
Labels: refactoring

#1367 feat(push): add server non response control
  src/pushNotifications/PermissionHandling.ts
  src/pushNotifications/TokenHandling.ts
Labels: enhancement, personalized push

#1378 feat(tiles): add space between tiles in last row
  src/components/screens/ServiceTile.tsx
Labels: bug
