Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2025-01, with the labels that each got.

#1229 feat(events): remove deprecated `listingWithoutDateFragment`
  src/components/Calendar.tsx
  src/components/CrossData.tsx
  src/components/screens/EventRecords.js
  src/components/widgets/EventWidget.tsx
  src/queries/eventRecords.js
  src/queries/index.js
  src/queries/types.ts
Labels: enhancement

#1227 fix(oparl): organisation dropdown select
  src/screens/OParl/OParlOrganisationsScreen.tsx
  src/screens/OParl/OParlPersonsScreen.tsx
  src/screens/OParl/OParlSearchScreen.tsx
Labels: bug

#1230 chore(expo): update expo version to 52
  app.json
  package.json
  src/components/Chat.js
  src/components/Modal.tsx
  src/components/screens/Overviews.js
  src/helpers/cameraHelper.ts
  src/hooks/HomeRefresh.ts
  src/hooks/imagePicker.ts
  src/screens/EncounterScannerScreen.tsx
  src/screens/HomeScreen.js
  src/screens/Voucher/VoucherScannerScreen.tsx
  yarn.lock
Labels: enhancement

#1197 **EPIC** Filter feature
  src/ConfigurationsProvider.tsx
  src/PermanentFilterProvider.tsx
  src/components/Calendar.tsx
  src/components/Checkbox.js
  src/components/DropdownHeader.js
  src/components/DropdownSelect.js
  src/components/SUE/report/SueReportUser.tsx
  src/components/defectReport/DefectReportCreateForm.tsx
  src/components/filter/DateFilter.tsx
  src/components/filter/DropdownFilter.tsx
  src/components/filter/Filter.tsx
  src/components/filter/FilterComponent.tsx
  src/components/filter/SliderFilter.tsx
  src/components/filter/Sue/StatusFilter.tsx
  src/components/map/LocationOverview.tsx
  src/components/map/Map.tsx
  src/components/noticeboard/NoticeboardCreateForm.tsx
  src/components/noticeboard/NoticeboardMessageForm.tsx
  src/components/screens/EventRecords.js
  src/components/screens/Overviews.js
  src/components/settings/PermanentFilterSettings.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/components/volunteer/VolunteerFormGroup.tsx
  src/components/volunteer/VolunteerFormProfile.tsx
  src/components/widgets/EventWidget.tsx
  src/config/appDesignSystem/filter.ts
  src/config/appDesignSystem/index.ts
  src/config/consts.js
  src/config/texts.js
  src/helpers/filterObjectHelper.ts
  src/helpers/filterTypesHelper.ts
  src/helpers/geolocationRadiusFilterHelper.ts
  src/helpers/index.js
  src/helpers/parser/listItemParser.js
  src/helpers/updateResourceFiltersStateHelper.ts
  src/hooks/constructionSites.ts
  src/hooks/listHooks.js
  src/hooks/permanentFilter.ts
  src/queries/eventRecords.js
  src/queries/index.js
  src/queries/newsItems.js
  src/queries/resourceFilters.ts
  src/queries/types.ts
  src/reducers/index.ts
  src/reducers/permanentFilterReducer.ts
  src/reducers/resourceFiltersReducer.ts
  src/screens/ConstructionSiteDetailScreen.js
  src/screens/ConstructionSiteOverviewScreen.js
  src/screens/Noticeboard/NoticeboardIndexScreen.tsx
  src/screens/SUE/SueListScreen.tsx
  src/screens/SUE/SueReportScreen.tsx
  src/types/GenericType.ts
  src/types/PermanentFilter.ts
  src/types/ResourceFilters.ts
  src/types/index.ts
Labels: enhancement, filter

#1226 feat(tab): configureable tab navigation
  src/components/OrientationAwareIcon.tsx
  src/config/navigation/defaultStackConfig.tsx
  src/config/navigation/tabConfig.tsx
  src/navigation/MainTabNavigator.tsx
  src/types/Navigation.ts
Labels: enhancement

#931 feat: add more information in the preview
  src/components/TextListItem.tsx
  src/components/map/LocationOverview.tsx
Labels: enhancement

#1228 feat(eas): build and submit configuration
  app.json
  eas.json
  package.json
Labels: enhancement

#1236 feat(maestro): introduce maestro for e2e testing
  __maestro__/clear-state.yml
  __maestro__/config.yml
  __maestro__/flows/bookmarks/overview.yml
  __maestro__/setup/app-start.yml
  __maestro__/setup/index.yml
  __maestro__/setup/onboarding.yml
  __maestro__/setup/with-state.yml
  __maestro__/setup/without-state.yml
  package.json
Labels: enhancement

#1238 fix: add prop to wrapper
  src/components/CardListItem.js
  src/components/CommentSection.tsx
  src/components/Disturber.tsx
  src/components/InfoHeader.tsx
  src/components/SUE/report/SueReportDescription.tsx
  src/components/SUE/report/SueReportLocation.tsx
  src/components/SUE/report/SueReportUser.tsx
  src/components/Wrapper.js
  src/components/defectReport/DefectReportCreateForm.tsx
  src/components/encounter/EncounterList.tsx
  src/components/filter/Filter.tsx
  src/components/noticeboard/NoticeboardCreateForm.tsx
  src/components/noticeboard/NoticeboardMessageForm.tsx
  src/components/oParl/File.tsx
  src/components/profile/LoginModal.tsx
  src/components/profile/noticeboard/ProfileNoticeboardCreateForm.tsx
  src/components/screens/consul/Debates/NewDebate.js
  src/components/screens/consul/Proposals/NewProposal.js
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/components/volunteer/VolunteerFormConversation.tsx
  src/components/volunteer/VolunteerFormGroup.tsx
  src/components/volunteer/VolunteerFormProfile.tsx
  src/components/vouchers/VoucherRedeem.tsx
  src/components/whistleblow/WhistleblowReportCode.tsx
  src/components/whistleblow/WhistleblowReportForm.tsx
  src/screens/AppIntroScreen.tsx
  src/screens/EncounterDataScreen.tsx
  src/screens/EncounterRegistrationScreen.tsx
  src/screens/FeedbackScreen.js
  src/screens/OParl/OParlPersonsScreen.tsx
  src/screens/SUE/SueDetailScreen.tsx
  src/screens/Voucher/VoucherDetailScreen.tsx
  src/screens/Voucher/VoucherLoginScreen.tsx
  src/screens/consul/LoginRegister/ConsulLoginScreen.js
  src/screens/consul/LoginRegister/ConsulRegisterScreen.js
  src/screens/profile/ProfileDeleteScreen.tsx
  src/screens/profile/ProfileEditMailScreen.tsx
  src/screens/profile/ProfileEditPasswordScreen.tsx
  src/screens/profile/ProfileHomeScreen.tsx
  src/screens/profile/ProfileLoginScreen.tsx
  src/screens/profile/ProfileRegistrationScreen.tsx
  src/screens/profile/ProfileResetPasswordScreen.tsx
  src/screens/profile/ProfileUpdateScreen.tsx
  src/screens/volunteer/VolunteerLoginScreen.tsx
  src/screens/volunteer/VolunteerRegistrationScreen.tsx
  src/screens/volunteer/VolunteerSignupScreen.tsx
Labels: bug

#1239 fix(sue): reduce returns on sue report screen
  src/helpers/textHelper.js
  src/screens/SUE/SueReportScreen.tsx
  src/screens/SettingsScreen.js
Labels: bug
