Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2025-07, with the labels that each got.

#1342 feat: add button to carousel
  src/components/Button.js
  src/components/Image.js
  src/components/ImageButton.tsx
  src/components/ImagesCarousel.js
  src/components/ImagesCarouselItem.js
Labels: enhancement, sue

#1338 fix: app push switcher is always on
  src/pushNotifications/PermissionHandling.ts
Labels: bug

#1350 Search 0.0.1-beta
  app.json
  patches/react-native-elements+3.4.3.patch
  src/components/HeaderRight.tsx
  src/components/SearchHeader.tsx
  src/components/index.js
  src/components/search/Search.tsx
  src/components/search/SearchResultSectionList.tsx
  src/components/search/index.ts
  src/config/consts.js
  src/config/icons/Icon.tsx
  src/config/navigation/defaultStackConfig.tsx
  src/config/texts.js
  src/hooks/listHooks.js
  src/index.js
  src/navigation/screenOptions.tsx
  src/queries/index.js
  src/queries/search.ts
  src/queries/types.ts
  src/screens/SearchScreen.tsx
  src/screens/index.js
  src/types/Navigation.ts
Labels: enhancement, search

#1348 feat: add inputs for carpool module
  patches/react-native-gifted-chat+2.7.3.patch
  src/components/noticeboard/NoticeboardCreateForm.tsx
  src/components/profile/LoginModal.tsx
  src/components/profile/noticeboard/ProfileNoticeboardCreateForm.tsx
  src/components/screens/Overviews.js
  src/components/screens/noticeboard/NoticeboardDetail.tsx
  src/config/texts.js
  src/helpers/parser/listItemParser.js
  src/queries/genericItem.js
  src/screens/HtmlScreen.js
  src/screens/NestedInfoScreen.tsx
  src/screens/Noticeboard/NoticeboardFormScreen.tsx
  src/screens/Noticeboard/NoticeboardIndexScreen.tsx
  src/screens/Noticeboard/NoticeboardMemberIndexScreen.tsx
  src/screens/profile/ProfileLoginScreen.tsx
Labels: enhancement

#1357 feat(android): upgrade target sdk version to 35
  app.json
Labels: enhancement
