Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2025-03, with the labels that each got.

#1284 fix: enhance filtering logic in dropdown and overview components
  src/components/DropdownHeader.js
  src/components/filter/Filter.tsx
  src/components/screens/Overviews.js
Labels: bug

#1287 feat: implement `MB_TO_BYTES` constant for file size checks
  src/components/Chat.js
  src/components/selectors/DocumentSelector.tsx
  src/components/volunteer/VolunteerFormCalendar.tsx
  src/config/consts.js
  src/config/texts.js
  src/helpers/consul/dataErrorMessageGenerator.js
  src/screens/SUE/SueReportScreen.tsx
Labels: enhancement

#1289 refactor: replace inline styles with style objects to reduce re-renderings
  src/components/Calendar.tsx
  src/components/EventList.js
  src/components/GroupedListItem.tsx
  src/components/TextListItem.tsx
  src/components/waste/WasteCollectionListItem.tsx
  src/hooks/listHooks.js
  src/screens/AppIntroScreen.tsx
  src/screens/WebScreen.tsx
Labels: refactoring

#1286 fix: conditionally render count in `DefaultWidget` component
  src/components/widgets/DefaultWidget.tsx
Labels: bug

#1288 fix(navigation): update tab bar style for better appearance
  src/navigation/MainTabNavigator.tsx
  src/navigation/screenOptions.tsx
Labels: enhancement

#1290 refactor: introduce RootView
  App.js
  src/RootView.tsx
  src/index.js
Labels: refactoring

#1291 fix(opening times): check more explicitly to catch edge cases
  src/components/screens/OpeningTimesCard.js
Labels: bug

#1295 feat(update): integrate in-app updates functionality
  app.json
  app.json.erb.tmpl
  package.json
  src/config/texts.js
  src/hooks/versionCheck.ts
  yarn.lock
Labels: enhancement

#1296 feat(event): remove dates from sub list in calendar view
  src/components/Calendar.tsx
  src/components/VerticalList.js
  src/components/screens/EventRecords.js
  src/hooks/listHooks.js
Labels: enhancement
