Repository smart-village-solutions/smart-village-app-app, pull requests merged in 2025-05, with the labels that each got.

#1324 feat(sue): make the feedback form updatable via main-server
  src/components/SUE/report/SueReportSend.tsx
Labels: enhancement, sue

#1323 feat(sue): update pin on report screen
  src/components/SUE/report/SueReportLocation.tsx
  src/components/map/Map.tsx
  src/screens/SUE/SueMapViewScreen.tsx
Labels: enhancement, sue

#1293 feat(onboarding): add 'skip' option to app intro
  src/components/Checkbox.js
  src/config/texts.js
  src/screens/AppIntroScreen.tsx
Labels: enhancement

#1314 feat(map): add pin to map
  src/components/map/MapLibre.tsx
Labels: enhancement

#1315 feat(map): integrate maplibre package into full screen map
  src/components/map/MapLibre.tsx
  src/screens/MapScreen.tsx
  src/screens/MapViewScreen.js
Labels: enhancement

#1316 feat(map): add polyline attribute
  src/components/map/MapLibre.tsx
Labels: enhancement

#1317 feat(map): add the ability to show a different icon when selected
  src/components/map/MapLibre.tsx
  src/screens/SUE/SueMapScreen.tsx
Labels: enhancement

#1318 feat(map): add the ability to generate an address from the selected location
  src/components/map/MapLibre.tsx
Labels: enhancement

#1319 feat(map): simplify MarkerView usage and adjust callout margin
  src/components/SUE/report/SueReportLocation.tsx
  src/components/map/MapLibre.tsx
  src/screens/SUE/SueMapViewScreen.tsx
Labels: bug

#1297 feat(waste): improve waste calendar performance
  src/components/waste/WasteInputForm.tsx
  src/config/texts.js
  src/hooks/waste.tsx
  src/queries/waste.js
  src/screens/WasteCollectionScreen.js
  src/screens/WasteCollectionSettingsScreen.tsx
Labels: enhancement

#1326 fix(map): the problem of not being able to add pins to the map
  src/components/SUE/report/SueReportLocation.tsx
  src/components/map/MapLibre.tsx
  src/screens/SUE/SueMapScreen.tsx
  src/screens/SUE/SueMapViewScreen.tsx
Labels: bug, map

#1328 feat(map): return enhancements and align several code spots
  src/components/SUE/report/SueReportLocation.tsx
  src/components/augmentedReality/AugmentedReality.js
  src/components/map/MapLibre.tsx
  src/components/screens/PointOfInterest.js
  src/screens/MapScreen.tsx
  src/screens/MapViewScreen.js
  src/screens/SUE/SueDetailScreen.tsx
  src/screens/SUE/SueMapScreen.tsx
  src/screens/SUE/SueMapViewScreen.tsx
Labels: enhancement, refactoring, map
